### ISSUE TITLE
Accented characters in facet names cause issues

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/solr-power#125]
Similarly to how we are escaping characters like ampersand we need to escape accented characters.

Facet names with accented characters, e.g. "Room Décor", return no results when there are some.

**Comment by Ritesh-patel** [comment]
@ataylorme @allan23 I created a post with `Room Décor` post title and can see that post in search result when I tried to search `Décor`. Not sure if this is still valid or correct me if I am wrong.

**Comment by allan23** [comment]
@Ritesh-patel instead of a post, create a category or a custom field with that name.

**Comment by Ritesh-patel** [comment]
@allan23 it's working fine with category as well. Couldn't check with custom field as it isn't added yet.

**Comment by ataylorme** [comment]
@Ritesh-patel Are you using standard search? This bug is for the facet widget. When faceted items, such as category, have an accented character they return no results.

See [this search](http://dev-solr-power.pantheonsite.io/?s=apple) on the example site. If you add the facet for the `All Kids' Furniture & Room Décor` category there are no results (there should be three). Other categories work as expected.

**Comment by Ritesh-patel** [comment]
@ataylorme now I see it, thanks for the info :)

**Comment by Ritesh-patel** [comment]
@ataylorme I assigned following 3 categories to "Hello World" post. 

- Room Décor
- All Kids' Furniture & Room Décor
- All Kids' Furniture & test

When I search for "Hello" in facet widget, I can see these 3 categories to filter. The `Room Décor` category is working fine for me in facet widget but not `All Kids' Furniture & Room Décor` and `All Kids' Furniture & test`. So I think issue is not with accented characters but special characters?

**Comment by Ritesh-patel** [comment]
@ataylorme @allan23 
Update to my last comment:  I added two more categories "100$ posts" and "100$’ posts". Only `100$’ posts` fails. So I think it's not special characters but specific to apostrophe (') ?

**Comment by ataylorme** [comment]
@Ritesh-patel that may be true and it was just a coincidence that the item I tested had both.

**Comment by ataylorme** [comment]
@Ritesh-patel the goal would be for all of these variations to work without issue. Your latest comment looks like the quote conversion might be the result of [wptexturize](https://codex.wordpress.org/Function_Reference/wptexturize)

**Comment by Ritesh-patel** [comment]
#137 fixes single quote in facet issue.
