### ISSUE TITLE
Return facets in full text search results

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/solr-power#126]
Solr search should return matches for facets in full text search. For example, if a post has the category "Movie" it should return in the results for the query "movie".

Facets values, such as category, should be considered but scored less than post title or content.

**Comment by allan23** [comment]
@ataylorme Looking at this, can't we just implement a boost function that scores post_title and post_content higher than everything else?

**Comment by ataylorme** [comment]
@allan23 - Yes, that makes sense to me.
