### ISSUE TITLE
Is there a way to query by post_date range?

### ISSUE THREAD

**Issue by Paul7200** [pantheon-systems/solr-power#131]
I'm trying to get all the posts between date X and Y, but can't seem to find a good solution. From what I can gather from documentation and in the Schema file it appears '`q=somequery&post_date:[2000-01-01T00:00:00Z TO 2015-12-314T23:59:99.999Z]`' should do the trick, but no such luck.

**Comment by ataylorme** [comment]
Hi @Paul7200,
We're currently working on implementing support with `WP_Query` ([#17](https://github.com/pantheon-systems/solr-power/issues/17)) which will make querying by date easy.

**Comment by ataylorme** [comment]
Hi @Paul7200,
Using the latest version of the plugin you should be able to query dates easily with `WP_Query`.

See [examples/example.custom_WP_Query.php](https://github.com/pantheon-systems/solr-power/blob/master/examples/example.custom_WP_Query.php)
