### ISSUE TITLE
Possible to install the plugin in Non Pantheon servers such as linode ?

### ISSUE THREAD

**Issue by djrules24** [pantheon-systems/solr-power#134]
Solr Configuration
Ping Status:    Failed
Solr Server IP address: 139.162.44.105
Solr Server Port:   8983
Solr Server Path:   /sites/self/environments//index

How do you change the solr server path

**Comment by ataylorme** [comment]
Hi @djrules24,
Yes, see [#3 in the Installation section of the README](https://github.com/pantheon-systems/solr-power#installation).

> Configuring Solr Power to use this particular Solr instance by setting the PANTHEON_INDEX_HOST and PANTHEON_INDEX_PORT environment variables.

You just need to set those environment variables.

**Comment by djrules24** [comment]
I have done the following
-> I have placed the following in the wp-config pointing to my server 
putenv( 'PANTHEON_INDEX_HOST=192.168.50.4' ); // Replace with the appropriate IP address
putenv( 'PANTHEON_INDEX_PORT=8983' );
-> I have placed the following in functions.php
add_filter( 'solr_scheme', function(){ return 'http'; });
-> I have changed the solr server path in api.php in your plugin directory

What I would like to do is achieve the following
-> As the post is created the SOLR index should be added
-> The summary page isnt displaying the count though on calling a direct solr URL displays the search results available in index
-> Short code to view the Solr search results

**Comment by ataylorme** [comment]
Hi @djrules24,
> -> As the post is created the SOLR index should be added

You'll need to do an initial index from the Solr Power plugin options page for existing posts. After that newly created posts should be indexed as well.

By default posts with the post type `post` are indexed. You can use the plugin options or the filter `solr_post_types` to add additional post types to be indexed. If you update the post types to be indexed you will need to re-index.

> -> The summary page isnt displaying the count though on calling a direct solr URL displays the search results available in index

Your archive pages won't use Solr by default when enabling the plugin.

> -> Short code to view the Solr search results

We don't have a shortcode for you to use at the moment. We are working on [`WP_Query` support](https://github.com/pantheon-systems/solr-power/issues/17) so you could use `WP_Query` directly when that is finished or create your own shortcode.

In the meantime there is the faceted search widget. If you would like to use it outside of a widget area, like in a template, you can do so with the [`solr_facet_search` function](https://github.com/pantheon-systems/solr-power/blob/master/includes/class-solrpower-facet-widget.php#L235:L246).

The facet widget and accompanying function work with WordPress search out of the box.

**Comment by ataylorme** [comment]
> We don't have a shortcode for you to use at the moment. We are working on `WP_Query` support so you could use WP_Query directly when that is finished or create your own shortcode.

Just wanted to note that partial `WP_Query` support has been released.
