### ISSUE TITLE
More detailed instructions for running locally

### ISSUE THREAD

**Issue by jon-heller** [pantheon-systems/solr-power#138]
I found I needed to do a lot of configuration to get this running locally, including downloading an older version of Solr and adding an environment variable. I wrote out some instructions, maybe for the Wiki if they're helpful.

----

## Installing Solr

Install Java, if you haven't already

```
sudo apt-get -y install openjdk-7-jdk`
mkdir /usr/java`
ln -s /usr/lib/jvm/java-7-openjdk-amd64 /usr/java/default
```

Next install a 4.X version of Solr (this example uses 4.7.2). This is important as the schema.xml file used by Pantheon is not supported in newer Solr versions. 

```
cd /opt
wget http://archive.apache.org/dist/lucene/solr/4.7.2/solr-4.7.2.tgz
tar -xvf solr-4.7.2.tgz
cp -R solr-4.7.2/example /opt/solr
cd /opt/solr
java -jar start.jar
```

Check if it works by visiting http://YOUR_IP:8983/solr. It is possible to have this start as a service using Tomcat or Jetty, but that isn't covered in these docs.

## Creating a WordPress collection in Solr

First, renamed the default `collection` to `wordpress`

```
cd /opt/solr/solr
mv collection1 wordpress
cd wordpress
```

Rename the collection in the `core.properties` file as well.

Then remove the default data directory

`rm -R data`

Next, you need to paste the `schema.xml` file in the [root of the WordPress Solr plugin](https://github.com/pantheon-systems/solr-power/blob/master/schema.xml) and paste the contents into `conf/schema.xml`. An easy solution to this is to delete the default and paste the new content into an empty file.

Now go back to `/opt/solr` and `java -jar start.jar`. 

## Configure WordPress to talk to Solr

Download the [WordPress Solr](https://wordpress.org/plugins/solr-power/) plugin, but don't activate it yet. 

If you don't have one yet, created a must-use plugins directory in your WordPress install (`/wp-content/plugins/mu-plugins`). Inside that directory, create a file `solr.php` and paste in the following

```
<?php

putenv( 'PANTHEON_INDEX_HOST=192.168.50.42' ); // Replace with the appropriate IP address
putenv( 'PANTHEON_INDEX_PORT=8983' );
define( 'SOLR_PATH', '/solr/wordpress/' );
add_filter( 'solr_scheme', function(){ return 'http'; });
```

Finally, activate the Solr plugin. You should be able to go to the Solr options in WordPress and build the index. 

Remember that you have to keep Solr running in your SSH shell unless you set it up as a service.

**Comment by ataylorme** [comment]
Hi @jon-heller,
Thank you for the very detailed writeup. This would be a great addition to the wiki or README. What OS and version are you on? The use of `apt-get` suggest a Debian system, like Ubuntu. I would prefer to create a page for each this OS and maybe add others, like OSX, in the future.

Cheers,
Andrew

**Comment by ataylorme** [comment]
@jon-heller - I'm also curious if you tried using [the existing installation instructions](https://github.com/pantheon-systems/solr-power#installation), which make use of [`bin/install-solr.sh`](https://github.com/pantheon-systems/solr-power/blob/master/bin/install-solr.sh)

**Comment by jon-heller** [comment]
Hi @ataylorme,

Glad it sounds helpful! This was done on Ubuntu 14.04. 

As for `bin/install-solr.sh`, that unfortunately doesn't appear to exist in Solr 4.*, which is why I had to add those manual steps to move and start it.

**Comment by ataylorme** [comment]
@jon-heller `bin/install-solr.sh` is a script in the Solr Power plugin repo. It's what we use to install Solr for automated tests. It does many of the steps you have listed, such as downloading Solr, copying the `schema.xml`, and starting Solr service.

**Comment by jon-heller** [comment]
Hah, you're right. I saw the line in the instructions which says

`Run ./bin/install-solr.sh to install and run Apache Solr on port 8983.`

but thought that was referring to the script in the Solr codebase, which is `bin/install_solr_service.sh`. But you're right, the script in this repo takes care of the installation and collection creation. So maybe it's just the `SOLR_PATH` environment variable that still needs to be set? I'm not sure if the script also takes care of that.

**Comment by ataylorme** [comment]
@jon-heller 

> So maybe it's just the SOLR_PATH environment variable that still needs to be set? I'm not sure if the script also takes care of that.

Nope, the script simply installs Solr. Your section on _Configure WordPress to talk to Solr_ is still very useful. Our instructions include didn't include setting the Solr path.

I updated our README. Can you take a look at [the updated instructions](https://github.com/pantheon-systems/solr-power#installation) and see if they make sense?

**Comment by jon-heller** [comment]
@ataylorme Yep, looks good!

**Comment by ataylorme** [comment]
Awesome - thanks @jon-heller. Closing this out. As an aside we're working on `WP_Query` support. Would you be interested in helping us test?
