### ISSUE TITLE
Fallback to WP Query if solr search in not reachable

### ISSUE THREAD

**Issue by Ritesh-patel** [pantheon-systems/solr-power#139]
If solr search is not reachable than it should fallback to WordPress' WP Query.

**Comment by ataylorme** [comment]
+1 on this. @allan23 can you incorporate into the `WP_Query` branch you are working on?

**Comment by ataylorme** [comment]
@allan23 - I wanted to bump this. I think it's pretty low hanging fruit and something we can ship in the next release.

**Comment by ataylorme** [comment]
To be clear we should be falling back to the WordPress defaults for `WP_Query` and search if the plugin is installed and activated but Solr is not available.

This will probably be checking if Solr is available and only implementing hooks into those items if it is.
