### ISSUE TITLE
Update Solarium to 3.5.1

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/solr-power#14]
We should get up to 3.3.0. However this is not a priority for the first (alpha) release.

**Comment by joshkoenig** [comment]
It's up to 3.5.1 now! We should also standardize a build/test process here. 

https://github.com/solariumphp/solarium/releases

**Comment by joshkoenig** [comment]
Also, make sure we've removed any hacks that went into Solarium.

**Comment by ataylorme** [comment]
Removing the 0.4 milestone. Since this isn't a new feature, just some internal cleanup, it can be a patch version bump instead of a minor release and shouldn't hold up other, new features for 0.4

**Comment by ataylorme** [comment]
Merged in #106
