### ISSUE TITLE
Illustrate clearly how to use Admin Query screen

### ISSUE THREAD

**Issue by dustinleblanc** [pantheon-systems/solr-power#150]
Folks typically expect the backend query screen to behave like a user facing search. We should provide an example of how to use this field in the readme and consider making the page more explicit about this being a "raw" solr query.

**Comment by ataylorme** [comment]
@dustinleblanc and @joshkoenig do you think the raw Solr query is something still useful for users? With `WP_Query` integration I the idea is that people don't need to interact with Solr directly as the plugin is handling it.

I'm personally in favor of just removing this tab to avoid confusing most folks and documenting the public method to run a direct query, maybe in the readme or Wiki, for the super advanced user that wants to do that.

**Comment by ataylorme** [comment]
Moving forward with removing the query tab from the admin interface.

Documentation on running a direct query with the `SolrPower_Api` class is on [this wiki page](https://github.com/pantheon-systems/solr-power/wiki/Interacting-with-the-SolrPower_Api-class).
