### ISSUE TITLE
Error when indexing via terminus

### ISSUE THREAD

**Issue by cjbos** [pantheon-systems/solr-power#153]
Hi,

I get a error here when indexing via terminus

https://github.com/pantheon-systems/solr-power/blob/master/includes/class-solrpower-sync.php#L304

Looks like id should be term_id instead? (As per https://codex.wordpress.org/Function_Reference/get_the_tags)

**Comment by allan23** [comment]
Hi @cjbos,
Great catch. I'll submit a pull request shortly to correct this.

**Comment by cjbos** [comment]
Thanks! Btw this plugin is a godsend, thanks again!

**Comment by ataylorme** [comment]
@cjbos - this has been merged in. We're working on adding `date_query` support and don't plan to do another release until that is merged. You can download the master `.zip` from GitHub to test this fix until a new release is tagged and shipped to WordPress.org.
