### ISSUE TITLE
Admin UI improvements

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/solr-power#163]
The admin UI is pretty basic and could use some style/UI love. This needs more scoping/discovery.

<img width="974" alt="screen shot 2016-11-30 at 1 28 45 pm" src="https://cloud.githubusercontent.com/assets/2133004/20859940/e1daa508-b93a-11e6-998b-6bb21ac88a1b.png">

**Comment by joshkoenig** [comment]
We should consider splitting all the facet widget settings into it's own tab. It doesn't really belong under "indexing"

**Comment by ataylorme** [comment]
> We should consider splitting all the facet widget settings into it's own tab. It doesn't really belong under "indexing"

This was updated in #179 but some other visuals, like the icons shown in the image above, aren't implemented so leaving this issue open.

**Comment by ataylorme** [comment]
@joshkoenig can you review the admin UI updates on the `admin-ui` multidev?
