### ISSUE TITLE
Feature Request: Add a hook when indexing all posts has been completed

### ISSUE THREAD

**Issue by cjbos** [pantheon-systems/solr-power#164]
We have a few terms which we display as regular posts on our site, I've indexed them into solr as if they are posts via a cli command which is run after we re-index all the posts or load the terms. (These terms are pulled from an external source and not updated)

It would be really handle if we could have a hook of some sort once indexing all the posts has been completed so we don't have to manually run this command.

**Comment by ataylorme** [comment]
@cjbos adding this hook is a good idea. We're currently working on the next release so I'm assigning this to myself to get it added in.

**Comment by cjbos** [comment]
Great, thanks!

**Comment by ataylorme** [comment]
@cjbos The proposed action is `solr_power_index_all_finished` and will fire when indexing all posts, either from the settings panel or wp-cli, has finished.

Note that the Solr index also updates when individual posts are modified, deleted, etc. This action only fires for the bulk index, not indexing individual posts.

**Comment by cjbos** [comment]
Thanks!

**Comment by ataylorme** [comment]
We still have a few other features to finish before we cut a release but once this ships I'll let you know.
