### ISSUE TITLE
Alternate WP_Query() interface for powering complex queries

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/solr-power#17]
I am a big fan of what the boys at Alley Interactive did here:

https://github.com/alleyinteractive/es-wp-query

Making the Solr backed available for complex queries would be an excellent way to support scalability and speed for sites with a lot of content.

**Comment by ataylorme** [comment]
This should be as easy as adding a parameter to existing `WP_Query` calls.

**Comment by ataylorme** [comment]
@allan23 and @ChrisWiegman After chatting with @joshkoenig and having use case to back this up this issue should be top priority for the 1.0 milestone.

**Comment by ataylorme** [comment]
We're looking for something like [this](https://github.com/10up/ElasticPress#wp_query-and-the-elasticpress-query-integration)

```
new WP_Query( array(
    'solr_integrate'   => true,
    'post_type'      => 'post',
    'posts_per_page' => -1,
    'tax_query' => array(
        array(
            'taxonomy' => 'category',
            'terms'    => array( 'term-slug' ),
            'field'    => 'slug',
        ),
    ),
) );
```

**Comment by allan23** [comment]
@ataylorme Do we have more test cases in mind for this integration? I've got a few unit tests setup, but it would be ideal to have more scenarios. (https://github.com/allan23/solr-for-wordpress-on-pantheon/blob/feature/wp_query/tests/phpunit/test-solr.php#L523)

**Comment by ataylorme** [comment]
@allan23 Some tests on more complex custom field queries would be good. See [custom field parameters on the Codex page](https://codex.wordpress.org/Class_Reference/WP_Query#Custom_Field_Parameters) for some examples.

Tests with custom post types, in addition to the defaults, would be good as well.

**Comment by ataylorme** [comment]
@allan23 a few more use cases for testing:

1. WP_Query with a tax_query parameter
2. WP_Query with a date_query of "before" and a tax_query parameter
3. WP_Query with a tax_query parameter and an include_children flag
4. WP_Query with a date_query of "before" and a meta_query parameter

**Comment by ataylorme** [comment]
Another use case from #131 - multiple date queries, e.g. all posts between two dates.

**Comment by ataylorme** [comment]
Per chat with @allan23  we are going to split this into multiple pieces rather than one monolithic task.

- [ ] Basic `WP_Query` support (post/page, post type, author, status, pagination, return fields)
- [ ] Basic `meta_query` support (`=` and `!-` operators)
- [ ] `tax_query` support (built-in taxonomies and custom taxonomies)
- [ ] `date_query` support
- [ ] Full `meta_query` support (all operators)
- [ ] Full `WP_Query` support (category, tag, search, password, permission caching)

cc @joshkoenig

**Comment by joshkoenig** [comment]
That sounds good. I'll connect you with one of our customers who would be eager to try and put some of this code into action.

**Comment by ataylorme** [comment]
@joshkoenig we are missing a few operators, like regex, for `meta_query` but have almost full `WP_Query` coverage. I'm closing out and opening a new issue for complete coverage.
