### ISSUE TITLE
handle_modified() in SolrPower_Sync does not check to see if the modified post is searchable

### ISSUE THREAD

**Issue by cjbos** [pantheon-systems/solr-power#170]
I added a check against the modified post type and the searchable post types, to prevent non-searchable posts appearing in the search results.

Also I think this is a duplicate? https://github.com/pantheon-systems/solr-power/blob/master/includes/class-solrpower-sync.php#L58

**Comment by ataylorme** [comment]
Hi @cjbos,
> I added a check against the modified post type and the searchable post types, to prevent non-searchable posts appearing in the search results.

Can you submit this change as a pull request?

Also it looks like you are right on the duplicate line. If you want to remove that in your PR as well it would be fantastic.

Cheers,
Andrew

**Comment by cjbos** [comment]
Sure, https://github.com/pantheon-systems/solr-power/pull/171

Thanks!

**Comment by ataylorme** [comment]
Addressed by #171
