### ISSUE TITLE
Facet Widget UI Improvements

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/solr-power#172]
Collecting some UI notes for the out-of-the-box search facet widget before we go 1.0. We can add to this list as we do more testing/demos:

- [ ] When searching via AJAX, the facet UI should not fade in/out
- [ ] We should only supply "reset" links below facets that are selected

**Comment by ataylorme** [comment]
> When searching via AJAX, the facet UI should not fade in/out
@joshkoenig this is happening because the HTML of the div is being replaced with new data when results are updated since facets change.

I could _not_ replace the HTML and hide all facet inputs except the one selected with jQuery but that doesn't seem right either.

**Comment by joshkoenig** [comment]
> this is happening because the HTML of the div is being replaced with new data when results are updated since facets change

@ataylorme I'm saying that fade out/in is not the ideal visual effect for that UI transition. This is a separate content replacement than the search results. We should make it instant.

**Comment by ataylorme** [comment]
@joshkoenig Please test [this multidev](http://andrew-ajax-solr-power.pantheonsite.io/?s=*).

* Reset links only show up when a facet is selected
* Pagination works
* Facet UI doesn't fade in/out
* Cleaned up search result HTML

If all this looks good I'd like to merge this into your multidev and test on the theme you are building.
