### ISSUE TITLE
Support for WP_Query post__in and post__not_in

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/solr-power#180]
Missing some support, like regex operators on `meta_query`. Mostly there but would be nice to get complete coverage.

**Comment by rdanamcd** [comment]
I needed 'post__in' and 'post__not_in' queries. I did some simple modifications to the code to implement these two  ( but I'll have to update "class-solrpower-wp-query.php' each time though until fully integrated ).

For 'post__in' & 'post__not_in' I added it to variables $whitelist and $convert to the function "build_query" in "class-solrpower-wp-query.php". 'post__in' worked automatically. For 'post__not_in' I had to use the "apply_filters( 'solr_select_query', $select );" from "class-solrpower-api.php" to modify the $select before sending to Solr. Code below

Step 1:
`private function build_query( $query ) {
		$this->query = $query;
		$whitelist   = array(
			'post_type',
			'p',
			'page_id',
			'post_status',
			'post_parent',
			'name',
			'post__in',
			'post__not_in',
		);
		$convert     = array(
			'p'       => 'ID',
			'page_id' => 'ID',
			'name'    => 'post_name',
			'post__in' => 'ID',
			'post__not_in' => '!ID',
		);`

Step 2: ( just for 'post__not_in' )
`add_filter( 'solr_select_query', 'pif_solr_filter__solr_select_query' );
function pif_solr_filter__solr_select_query( $select ) {	
	$select['query'] = str_replace( '(!ID', '!(ID', $select['query'] );	
	return $select;
}`

This was just put together quickly and no serious testing. It's working for what I need ( and it's fast ).

Thanks
Dana

**Comment by ataylorme** [comment]
@danielbachhuber if you could take a look at this when you have time and open a proper PR with some tests that would be great

**Comment by AnaliaMok** [comment]
Was any further work or integration done on supporting the `post__in` and `post__not_in` arguments? Currently facing a problem where `post__not_in` would be helpful. 

Thanks in advance.

**Comment by danielbachhuber** [comment]
> Was any further work or integration done on supporting the `post__in` and `post__not_in` arguments?

It looks like it wasn't, and it's on me because I missed the ping. I can look into this in the next week or so, and I'd be happy to review a PR if you want to fix it before then.

**Comment by ghamok** [comment]
Thank you for the response,
I just submitted a pull request with more details #368

**Comment by danielbachhuber** [comment]
Fixed in #368
