### ISSUE TITLE
Can't search with wordpress 4.7.1

### ISSUE THREAD

**Issue by amtbnagios** [pantheon-systems/solr-power#186]
I installed solr 4.9.1 local on CentOS 6.8 with wordpress 4.7.1
solr power can Ping Success with Check Server Settings execute, and can 
Index Searchable Post Types success

I can search with solr - 10 records return
http://192.168.10.10:8983/solr/#/wordpress/query

solrlog like:
INFO  - 2017-01-20 20:17:11.948; org.apache.solr.core.SolrCore; [wordpress] webapp=/solr path=/select params={indent=true&q=*:*&_=1484914632676&wt=json} hits=10 status=0 QTime=3

But wordpress search String "Hello" return nothing,  solrlog like:
INFO  - 2017-01-20 20:22:30.967; org.apache.solr.core.SolrCore; [wordpress] webapp=/solr path=/select params={facet=true&sort=score+desc&fa
cet.mincount=1&facet.limit=10&hl.simple.pre=<b>&q.alt=Hello&hl.fl=post_content&json.nl=flat&wt=json&hl=true&rows=10&defType=dismax&hl.highl
ightMultiTerm=true&omitHeader=false&fl=*,score&start=0&q=&bf=post_title^25+post_content^50&q.op=AND&hl.simple.post=</b>&facet.field={!key%3
Dcategories}categories&facet.field={!key%3Dtags}tags&facet.field={!key%3Dpost_author}post_author&facet.field={!key%3Dpost_type}post_type&fa
cet.field={!key%3Dauthors_taxonomy}authors_taxonomy&facet.field={!key%3Daddress_taxonomy}address_taxonomy&facet.field={!key%3Dfiletype_taxo
nomy}filetype_taxonomy&facet.field={!key%3Dsource_taxonomy}source_taxonomy&facet.field={!key%3Dmbtype_taxonomy}mbtype_taxonomy&facet.field=
{!key%3Dauthorage_taxonomy}authorage_taxonomy&facet.field={!key%3Dmbsize_taxonomy}mbsize_taxonomy&facet.field={!key%3Dconsponsor_taxonomy}c
onsponsor_taxonomy&facet.field={!key%3Dpromoter_taxonomy}promoter_taxonomy&facet.field={!key%3Dmb_category_taxonomy}mb_category_taxonomy&fa
cet.field={!key%3Dletter_category_taxonomy}letter_category_taxonomy&facet.field={!key%3Dpicture_category_taxonomy}picture_category_taxonomy
&facet.field={!key%3Dphoto_category_taxonomy}photo_category_taxonomy&facet.field={!key%3Dspeech_category_taxonomy}speech_category_taxonomy&
facet.field={!key%3Dvideo_category_taxonomy}video_category_taxonomy&facet.field={!key%3Dactivity_category_taxonomy}activity_category_taxono
my&facet.field={!key%3Dmedia_category_taxonomy}media_category_taxonomy} status=500 QTime=97 
ERROR - 2017-01-20 20:22:30.971; org.apache.solr.common.SolrException; null:java.lang.UnsupportedOperationExceptio

Can any body help me, Thanks!

**Comment by danielbachhuber** [comment]
@amtbnagios It seems like this is your issue:

```
ERROR - 2017-01-20 20:22:30.971; org.apache.solr.common.SolrException; null:java.lang.UnsupportedOperationExceptio
```

I'm not sure Solr Power supports Solr 4.x. Pantheon's infrastructure currently deploys Solr 3.x. 

Can you try downgrading?

**Comment by acorbi** [comment]
@danielbachhuber @amtbnagios or someone reading this? Can you confirm whether Solr Power currently supports Solr 4.x or not?

**Comment by danielbachhuber** [comment]
> Can you confirm whether Solr Power currently supports Solr 4.x or not?

I don't believe so, no. Solr Power works fine with 3.6.x but I'm not sure if anyone has successfully used it with 4.x

@joshkoenig Thoughts?

> Also, would be nice to add this bit of information on the README

Can do!

**Comment by joshkoenig** [comment]
Hey @amtbnagios - we don't test with version 4.x but it should be agnostic. It looks like your error message is getting cut off (the word "exception" ends without an "n") and that means it's not saying what part of the query failed.

Can you try and get the full error message? Also, can you verify that a simple ping from the admin interface works and that you were able to use the plugin to index your content?

**Comment by ataylorme** [comment]
Hi @amtbnagios,
There hasn't been any activity on this in some time so I'm closing the issue out. If you still have questions let us know.
