### ISSUE TITLE
Rename Project: "solr-power"

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/solr-power#19]
**facepalm** - http://martinfowler.com/bliki/TwoHardThings.html

In preparation for release, I shortened the name of this project, which created a conflict with an existing plugin upstream, as well as creating issues with the admin UI. Mea culpa.

**Alternate Names**

* Apache Solr for WordPress / `apachesolr-for-wordpress`
* SolrPress / `solrpress`

Feel free to add your own in the comments.

**Comment by joshkoenig** [comment]
The settings page should be back to loading, but this will require more work to completely disentangle.

**Comment by allan23** [comment]
@joshkoenig Have you decided on a name yet?

**Comment by joshkoenig** [comment]
@allan23 thanks for the ping. I think we should go for something a little more on the fun side of things and brand this. After some discussion, I think the namespace to snag is (drumroll....)

**solr-power**

This speaks to our aspiration to be more than just a post search replacement (though obviously that's job 1). I can rename this repo whenever you are ready, but I don't want to be disruptive.

**Comment by joshkoenig** [comment]
@allan23 to close this one out, do we need to rename any of the php files internally? E.g. `solr-for-wordpress-on-pantheon.php` doesn't seem to quite fit.

**Comment by allan23** [comment]
@joshkoenig You're right. It should be renamed to `solr-power.php`.
