### ISSUE TITLE
Better UX for restarting index process on large site

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/solr-power#191]
As a Solr Power user with 200k posts, it's painful to have the index process die unexpectedly halfway through.

It would be more enjoyable to have a better UX for restarting the index process on a large site. Couple of ideas:

* Include an `--offset` argument for the `wp solr index` command so I can restart the process after a certain number of posts.
* Create functionality where WordPress knows what posts are in the index, and thus which aren't, so it can limit the index process to only posts that aren't in the index.

**Comment by danielbachhuber** [comment]
Actually, because the `paged` query var is used in `wp solr index`, we wouldn't want to support `offset` directly, because `offset` overrides `paged` (and would break the iteration).

**Comment by danielbachhuber** [comment]
@ataylorme For the admin, what do you think about this?

### No index to resume

![image](https://cloud.githubusercontent.com/assets/36432/22353879/6f7b284e-e3d7-11e6-8b91-1b428758de1c.png)

### Index to resume

![image](https://cloud.githubusercontent.com/assets/36432/22353930/b7d2feb4-e3d7-11e6-965d-97aa940d8c92.png)

**Comment by ataylorme** [comment]
@danielbachhuber that looks good to me. I think a total would be nice (x/x posts indexed) but not necessary.

Since there is a resume would it be tough to add pause as well?

**Comment by danielbachhuber** [comment]
> Since there is a resume would it be tough to add pause as well?

It wouldn't be tough. I'm not convinced it's necessary, though.
