### ISSUE TITLE
Switch to Terminus 1.0 in CI scripts

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/solr-power#192]
Follow the pattern in https://github.com/lcache/wp-lcache/pull/110

@tessak22 and I are going to work on this at Agency Office Hours on Wednesday: https://pantheon.io/agencies/office-hours

**Comment by ataylorme** [comment]
@stevector did you get to this? If not I might be able to carve out some time.

**Comment by stevector** [comment]
@ataylorme, not in this repo. wp-saml-auth was the only one we did yesterday: https://github.com/pantheon-systems/wp-saml-auth/pull/52

I'll unassign myself here.
