### ISSUE TITLE
Cannot access settings on Multisite

### ISSUE THREAD

**Issue by acorbi** [pantheon-systems/solr-power#196]
I'm currently testing the plugin (see other Issues raised by me) and I have following problem while testing solr-power on a multisite instance:

The following error message is shown when I click on the settings link on the **Plugins** management screen:

![screenshot from 2017-01-25 16-51-55](https://cloud.githubusercontent.com/assets/384894/22297750/9786d8e2-e31e-11e6-8d03-752a2c760b83.png)

- This happens both when I network-activate the plugin and when I activate it on each site individually.
- The user I am trying this with has Administrator role.
- Also, worth to note is that the **Solr options** menu item is not appearing on the sidebar of the WP dashboard.

Any ideas?

**Comment by ataylorme** [comment]
@acorbi what version of the plugin are you using?

**Comment by acorbi** [comment]
1.0.0 the one found on https://wordpress.org/plugins/solr-power/ and which I installed from the WP dashboard. is it the latest version?

**Comment by ataylorme** [comment]
Yes, `1.0.0` is the latest version. I just wanted to make sure I test with the same version you are using.

**Comment by ataylorme** [comment]
> Also, worth to note is that the Solr options menu item is not appearing on the sidebar of the WP dashboard.

@acorbi Solr Power doesn't currently support multisite (see #41). I looked into this and it is not a trivial amount of work to implement. Multisite support will probably need a release of it's own.

**Comment by acorbi** [comment]
Thanks for the infos @ataylorme. Me and the team at http://github.com/OpenDevelopmentMekong/ are currently analyzing the benefits, challenges and possibilities to collaborate on the further development of this plugin. Will keep you posted in case we can dedicate some resources for this.

**Comment by ataylorme** [comment]
@acorbi collaboration would be most welcome. I'm closing out this issue but feel free to reach out to me if you decide to collaborate and we can chat next steps.
