### ISSUE TITLE
Installing Solr 3.6 on a Mac

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/solr-power#199]
I found these instructions to be useful: https://helpcenter.woodwing.com/hc/en-us/articles/204805509-Step-1-Installing-Solr-3-6#on-mac-os-x

Because Solr Power doesn't support submitting `schema.xml` outside of Pantheon, it took me a while to figure out the `schema.xml` from the plugin needs to go to `~/solr/solr/conf/schema.xml`

Should we have Mac installation instructions in `readme.txt` ?

**Comment by ataylorme** [comment]
> Should we have Mac installation instructions in readme.txt ?

I think OS specific instructions could be on the Wiki. We can then link to the Wiki from the readme to keep the readme from getting too bloated. We can then break the existing Linux installation instructions out into the Wiki as well.

@joshkoenig thoughts on this approach?
