### ISSUE TITLE
Better UX for Solr index failures on large batch indexes

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/solr-power#202]
Performing an initial index on a large site is a time-consuming process. Because it's a time-consuming process, a little bit of brokenness can be significantly painful.

For instance, take this example where 16990 items have failed to index:

```
$ terminus wp solr-demo-redux.dev -- solr index
Resuming index at page 511...
tput: No value for $TERM and no -T specified
Indexing Items:  100% [========================================] 73:29  / 289:30
Success: 32470 of 202458 items indexed.
Error: Failed to index 16990 item(s).
```

Ugh. Of my total data (202458 items), a quarter hasn't ended up in the index (46434). How do I even deal with this?

Here are a couple of ideas for how Solr Power could better handle this for me:

1. When an index submission fails for a single item, try it once or twice again.
2. Keep some form of log of the failed items, and let me run the index process against just those items.

**Comment by danielbachhuber** [comment]
With #203, the error was pretty much inaccessible to me until I tried indexing locally and could look at the Solr logs for my local instance.

If indexing experienced an error, I'd expect to see the error right away (in both CLI and web UI) so I could take action on it and not have to wait until the process has completed to discover the issue.

**Comment by danielbachhuber** [comment]
New CLI output looks like this:

```
Failed to index '15/Love' (96): Solr HTTP error: HTTP request failed, Failed to connect to localhost port 8983: Connection refused
Failed to index '16 and Pregnant' (97): Solr HTTP error: HTTP request failed, Failed to connect to localhost port 8983: Connection refused
Failed to index '1600 Penn' (98): Solr HTTP error: HTTP request failed, Failed to connect to localhost port 8983: Connection refused
Failed to index '"1628 eller Regalskeppet Wasans uppbyggnad och underg' (99): Solr HTTP error: HTTP request failed, Failed to connect to localhost port 8983: Connection refused
Failed to index '17 - o poveste despre destin' (100): Solr HTTP error: HTTP request failed, Failed to connect to localhost port 8983: Connection refused
Failed to index '18 & Over' (101): Solr HTTP error: HTTP request failed, Failed to connect to localhost port 8983: Connection refused

Starting batch 2 of 54 at 0:00:02 elapsed time (0 indexed, 100 failed, 5294 remaining)

Failed to index '18 Wheels of Justice' (102): Solr HTTP error: HTTP request failed, Failed to connect to localhost port 8983: Connection refused
Failed to index '18 vs. 29' (103): Solr HTTP error: HTTP request failed, Failed to connect to localhost port 8983: Connection refused
Failed to index '180 Days: A Year Inside an American High School' (104): Solr HTTP error: HTTP request failed, Failed to connect to localhost port 8983: Connection refused
Failed to index '180 Degree' (105): Solr HTTP error: HTTP request failed, Failed to connect to localhost port 8983: Connection refused
Failed to index '1864' (106): Solr HTTP error: HTTP request failed, Failed to connect to localhost port 8983: Connection refused
Failed to index '19-2' (107): Solr HTTP error: HTTP request failed, Failed to connect to localhost port 8983: Connection refused
```

**Comment by ataylorme** [comment]
@danielbachhuber it scrolls pretty fast (screenshot below). Can we remove success messaged from the output and only show the items that encountered and error and batch information?

When things are going well I wouldn't see all the success messages and just the batch information with the nice summary which currently I have to back scroll to see since the output moves so fast.

![solr-power-wp-cli-index-output](https://cloud.githubusercontent.com/assets/2133004/23477347/5ab375bc-fe83-11e6-9161-8f88f13c9913.gif)

**Comment by danielbachhuber** [comment]
> Can we remove success messaged from the output and only show the items that encountered and error and batch information?

I'm 👎  on moving this information outright, because it's useful information in some cases.

> When things are going well I wouldn't see all the success messages and just the batch information with the nice summary which currently I have to back scroll to see since the output moves so fast.

You can also easily output to a log file, and then grep the log file for the results you're looking for.

I'd be open to a suggestion of a flag or two that'd control verbosity.

**Comment by ataylorme** [comment]
> You can also easily output to a log file, and then grep the log file for the results you're looking for.

Makes sense to me. Let's go with this as-is.
