### ISSUE TITLE
Unable excludes Posts or Pages from solr

### ISSUE THREAD

**Issue by harshadwebdunia** [pantheon-systems/solr-power#214]
When I tried to exclude an page using option provided by  plugin. It will not work.

**Comment by ataylorme** [comment]
@harshadwebdunia can you provide more details?

* What version of the plugin are you on?
* Are you trying to exclude an individual page or an entire post type?
* Which option we're you trying to use?
* After updating the option did you delete the index and re-index items?

**Comment by ataylorme** [comment]
Hi @harshadwebdunia,
There hasn't been any activity on this in some time so I'm closing the issue out. If you still have questions let us know.
