### ISSUE TITLE
Boosting hard-coded

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/solr-power#218]
> hi @ataylorme : regarding the front end issue, we located the issue (for us) = https://github.com/pantheon-systems/solr-power/blob/1.0.0/includes/class-solrpower-api.php#L359 this call dramatically changes the order of our search results ...

> is there a way to override or reset/unset those "hard-coded" values, ie, 'post_title^25 post_content^50'? (shouldn't boosting be a functionality open to use case?)

> and a quick question re: that line -- on = http://solarium.readthedocs.io/en/stable/queries/select-query/building-a-select-query/components/dismax-component/, the description of the boostFunctions method describes the string composed in the format: "funcA(arg1,arg2)^1.2 funcB(arg3,arg4)^2.2". are post_title and post_content references to functions?

`post_title` and `post_content` boosts are hard-coded. Boosts should, at a minimum, be filterable.

See [class-solrpower-api.php#L359](https://github.com/pantheon-systems/solr-power/blob/1.0.0/includes/class-solrpower-api.php#L359)

@aayler can you provide more details on how you are boosting?

**Comment by aayler** [comment]
Hi @ataylorme : we're using the setQueryFields method in the solr_query filter handler.

so something like = `$dismax->setQueryFields('post_title^2.5 tags^1.5');`

**Comment by ataylorme** [comment]
Just FYI the reason we set a boost to begin with is that when facets are used search results weren't really relevant. Adding a boost to title and content helped keep them relevant but _what_ is being boosted should be filterable.

**Comment by ataylorme** [comment]
@aayler can you test the changes in [946e0b12096a10d22bf3d56fd69cf24896895faa](https://github.com/pantheon-systems/solr-power/pull/219/commits/946e0b12096a10d22bf3d56fd69cf24896895faa) on your multidev?

You should be able to use the `solr_boost_query` filter to override the boost value of `post_title^25 post_content^50`.

**Comment by ataylorme** [comment]
Make that the [latest changes in the PR](https://github.com/pantheon-systems/solr-power/pull/219/files)

**Comment by aayler** [comment]
@ataylorme 👍  on our end re: filtering the `solr_boost_query`

thanks again!

**Comment by ataylorme** [comment]
@aayler great! I'll ask for a code review and merge this in for `1.1`. Once we tag `1.1` I'll ping you for testing if that's okay.

**Comment by aayler** [comment]
@ataylorme : absolutely, please do; would be glad to help test.

quick note: https://github.com/pantheon-systems/solr-power/pull/219/commits/946e0b12096a10d22bf3d56fd69cf24896895faa works but
https://github.com/pantheon-systems/solr-power/pull/219/files does not

**Comment by ataylorme** [comment]
Hmm okay, `946e0b1` with `setQueryFields` fails our unit tests for boosting but `boostFunctions` passes. Seems like you're seeing the opposite. I'll review the test.

**Comment by ataylorme** [comment]
@aayler can you test out https://github.com/pantheon-systems/solr-power/pull/219/files one more time?

This go around try:
1. setting the `solr_boost_query` filter to false, which will disable our boosting.
1. Hooking into the `solr_dismax_query` filter, which is new, and using `setQueryFields` on `$dismax`.

Something like:
```
add_filter( 'solr_boost_query', '__return_false' );

function my_namespace_solr_query( $dismax, $query ){
	$dismax->setQueryFields('post_title^2.5 tags^1.5');
	return $dismax;
}

add_action( 'solr_dismax_query', 'my_namespace_solr_dismax_query', 10, 2 );
```

**Comment by aayler** [comment]
@ataylorme : thanks for the update, will test now and reconnect

**Comment by aayler** [comment]
@ataylorme 🥇  looks good!

**Comment by ataylorme** [comment]
@aayler awesome - glad this worked out for both the widget/our tests and your implementation.

I merged in the PR and am looking to cut `1.1` later this afternoon. If you can test the `master` branch on your multidev that would be much appreciated.

**Comment by aayler** [comment]
@ataylorme : the vendor folder is empty in `master` and i'm seeing an error in a dependency = `vendor/autoload.php`, so the site's not loading ...

**Comment by ataylorme** [comment]
@aayler ah sorry, I should have specified the Git repo is not built. You'll need to run `composer install` and `Grunt`. Alternatively I can email you a `.zip` of the built plugin if that's easier for you.

**Comment by aayler** [comment]
@ataylorme : if it's not too much trouble, the .zip would be easier, thanks!
