### ISSUE TITLE
Options not saving properly

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/solr-power#22]
The options page is not saving preferences. Checkboxes are going un-saved, and key text fields are being filled-in by `Array`. This is the result after _un-checking_ "index pages" and then clicking "Save Changes":

![screen shot 2015-08-12 at 11 37 35 am](https://cloud.githubusercontent.com/assets/143186/9233222/b6c6223e-40e6-11e5-8d79-8fea5886c604.png)

Not "index pages" is still checked, and the two text fields below have `Array` as their value. 

Could be related to #19 as a name-spacing issue?

**Comment by rexington** [comment]
Don't know if this helps, but I get
`You do not have sufficient permissions to access this page.` 
when I try to save options.

**Comment by joshkoenig** [comment]
Yep fixed. Thanks!
