### ISSUE TITLE
Custom fields not searchable/Exclude selected posts

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/solr-power#224]
Overview:

1. We have added some of our custom fields "article_side_bar,subtitle" on the back end but unable to search on the basis of these fields.
Are custom data fields searchable?

2. How we can exclude some post type from indexing.
Also here I think: https://github.com/pantheon-systems/solr-power/issues/214

3. Unable to weight age (prioritize) the search fields like title, content etc.

4. As solr overwrite the default WordPress search behavior, is there any way to differentiate that it's WordPress default search or solr search.

Thanks!

**Comment by ataylorme** [comment]
What version of the plugin is being used? I'll be assuming `1.0` or later.

> We have added some of our custom fields "article_side_bar,subtitle" on the back end but unable to search on the basis of these fields. Are custom data fields searchable?

Yes, custom fields are indexable/searchable. In addition to adding custom fields in the admin settings you can use the [solr_index_custom_fields filter](https://github.com/pantheon-systems/solr-power/wiki/Filters#solr_index_custom_fields). After updating the custom fields to index did you re-index?

> How we can exclude some post type from indexing.

Non-public post types are excluded from indexing. The [`solr_post_types` filter](https://github.com/pantheon-systems/solr-power/wiki/Filters#solr_post_types) is also available if you wish to index only certain post types.

> Unable to weight age (prioritize) the search fields like title, content etc.

We will be having a new filter available in the next release allowing weighting of items. See [this comment on #218](https://github.com/pantheon-systems/solr-power/issues/218#issuecomment-283703865) for how that filter will work.

> As solr overwrite the default WordPress search behavior, is there any way to differentiate that it's WordPress default search or solr search.

For direct search, outside the widget, it should be seamless. 

In `1.x` of the plugin a template `templates/solr-search-results.php` is used for the Ajax widget search. You can override the template in the plugin by copying the `templates/solr-search-results.php` file into your theme and editing it. If the style is different than default search it will be easy to tell.

**Comment by AkshayMenariya** [comment]
Hi ataylorme,

Thank you for prompt reply. I am Akshay, ttrowell is created a issue for us. we are using WordPress "solr prower" plugin version  1.0.0.  I will try to index custom fields with the given filter and let you know, if it will work.

Thanks
Akshay

**Comment by ataylorme** [comment]
Hi @AkshayMenariya,
Sounds good. Since you are on Pantheon test the filter in a [multidev environment](https://pantheon.io/docs/multidev/). Just know after creating a multidev you'll need to re-index Solr after applying the filter as the database gets cloned to the multidev but not the Solr index.

**Comment by AkshayMenariya** [comment]
Hi ataylorme,

Solr is not reading custom search result template within theme "templates/solr-search-results.php". Also the custom fields are still not searchable.

I look forward to hearing from you soon.

Thanks
Akshay

**Comment by AkshayMenariya** [comment]
Hi @ataylorme ,

How should i pass all the custom fields to the below filter, it should be an array or comma separated fields ? please let me know if is there any other data format need to return.

function filter_solr_index_custom_fields( $facet_on_custom_fields ) {
    $custom_fields = array('article_side_bar','subtitle');
    return $custom_fields;
}
add_filter( 'solr_index_custom_fields', 'filter_solr_index_custom_fields', 10, 1 );

I have re index solr from the WordPress back end Solr Options->Indexing Options . Is there anything else need to do to re index the solr?

Thanks
Akshay

**Comment by ataylorme** [comment]
Hi @AkshayMenariya,
Sorry for the delayed reply, I am currently traveling.

> How should i pass all the custom fields to the below filter, it should be an array or comma separated fields ?

Returning an array will be best but the code can handle either. See [`includes/class-solrpower-sync.php`](https://github.com/pantheon-systems/solr-power/blob/master/includes/class-solrpower-sync.php#L182:L190)

> I have re index solr from the WordPress back end Solr Options->Indexing Options . Is there anything else need to do to re index the solr?

Also make sure the post types are `public` and not `private` or something else. The posts themselves will also need to be published and not have a different post status.

**Comment by ataylorme** [comment]
> Solr is not reading custom search result template within theme "templates/solr-search-results.php". 

This template is used with the faceted widget. Are you using the widget? Your normal search template will be used for default WordPress search.

**Comment by AkshayMenariya** [comment]
Hi @ataylorme ,

Thank you for reply. let me See includes/class-solrpower-sync.php class and will update you if it will work.


Thanks
Akshay

**Comment by ataylorme** [comment]
@AkshayMenariya,
In your code snippet you should append items to the existing array, rather than overwriting it. That way default fields, like post title and content, aren't removed.

Example:
```
function filter_solr_index_custom_fields( $solr_fields ) {
	$custom_fields = array( 'article_side_bar', 'subtitle' );

	return array_merge( $solr_fields, $custom_fields );
}

add_filter( 'solr_index_custom_fields', 'filter_solr_index_custom_fields', 10, 1 );
```

I've tested this as well as the custom post types successfully. We also have unit test coverage. See [`test-solr.php`](https://github.com/pantheon-systems/solr-power/blob/master/tests/phpunit/test-solr.php#L183:L205)

**Comment by AkshayMenariya** [comment]
Hi @ataylorme ,

Thanks for support, now i have customized your class " includes/class-solrpower-sync.php" to exclude post types and its working fine. I followed your give code & "build_document" function as well from " includes/class-solrpower-sync.php" file to index custom fields. I have checked with the "print & exit()" function, all the custom fields entered from the WordPress back end (comma separated) are showing in the "$doc" array but these fields are still not searchable, can you please look into it why these fields are not searchable and let me know the issue or is there anything which i am doing wrong here.

Thanks
Akshay Menariya

**Comment by AkshayMenariya** [comment]
Hi @ataylorme ,

How i can use <a href="https://github.com/pantheon-systems/solr-power/blob/master/tests/phpunit/test-solr.php#L183:L205"><code>test-solr.php</code></a> to test solr custom fields. Can i see search debug result on the back end or something which is helpful.

Thanks
Akshay

**Comment by ataylorme** [comment]
Hi @AkshayMenariya,

> Thanks for support, i have customized your class " includes/class-solrpower-sync.php" to exclude post types and its working fine.

I would advice against editing the Solr Power plugin files directly. It is best practice to use the provided filters. If you change the plugin files directly the modification can be overwritten if you update the plugin in the future.

> all the custom fields entered from the WordPress back end (comma separated) are showing in the "$doc" array but these fields are still not searchable, can you please look into it why these fields are not searchable and let me know the issue or is there anything which i am doing wrong here.

If the fields are showing up there they should be indexed. `test-solr.php` is our unit tests for the plugin and can't really be used to help with debugging. I would recommend disabling other plugins, especially those that modify the WordPress query or search, and see if the issue persists.

Also did you get my direct email about testing version `1.1`, which is still in development?

**Comment by AkshayMenariya** [comment]
Hi @ataylorme ,

Thank you for quick response, I first tried with the filter but it didn't work so i have to customized the core plugin and it worked. Regarding custom field theme and plugin conflicts, i have deactivate all the plugins and testing it on the default twentytwelve WordPress theme but it didn't worked. Is there any way to debug the custom field issue?

I got your latest plugin version 1.1 and testing it .

Thanks
Akshay

**Comment by AkshayMenariya** [comment]
Hi @ataylorme ,

Any update on my issue?

Thanks
Akshay

**Comment by ataylorme** [comment]
> Is there any way to debug the custom field issue?

You can run [a direct Solr query](https://github.com/pantheon-systems/solr-power/wiki/Interacting-with-the-SolrPower_Api-class) to see if the fields you are looking for exist in the index.
