### ISSUE TITLE
How to index fields from acf  "relationship" elements

### ISSUE THREAD

**Issue by danilogiacomi** [pantheon-systems/solr-power#225]
We are using the solrpower plugin to index some posts using ACF relations (relationship) and we'd like to index some fields from the related items along with the fields from the indexed item itself. 
Any ideas on how to do that?

**Comment by ataylorme** [comment]
Hi @danilogiacomi,
I just want to be sure I'm clear on what you are asking. If there is post *A* and has post *B* as an [ACF relationship](https://www.advancedcustomfields.com/resources/relationship/) you want to index some custom fields from post *B* on post *A*. Is that correct?

Indexing the relationship field itself should be pretty straight forward with the [`solr_index_custom_fields` filter](https://github.com/pantheon-systems/solr-power/wiki/Filters#solr_index_custom_fields).

For adding custom fields from post *B* to post *A* you would need to use the [`solr_build_document` filter](https://github.com/pantheon-systems/solr-power/wiki/Filters#solr_build_document). You can see how existing fields are added in [`includes/class-solrpower-sync.php`](https://github.com/pantheon-systems/solr-power/blob/c07c0171dbd5941c6e49bf1b8cb3b2d8aecbb1fe/includes/class-solrpower-sync.php#L192:L363) for reference when adding your custom fields for post *B*.

**Comment by ataylorme** [comment]
Hi @danilogiacomi,
There hasn't been any activity on this in some time so I'm closing the issue out. If you still have questions let us know.
