### ISSUE TITLE
Use slug instead of __FILE__

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/solr-power#23]
Per @allan23 we're best off using a consistent slug on these lines:

https://github.com/pantheon-systems/solr-for-wordpress/blob/master/solr-for-wordpress-on-pantheon.php#L1293

https://github.com/pantheon-systems/solr-for-wordpress/blob/master/solr-for-wordpress-on-pantheon.php#L1580

https://github.com/pantheon-systems/solr-for-wordpress/blob/master/solr-options-page.php#L205

We should make the slug align with the name we pick as resolution to #19

**Comment by havahula** [comment]
it looks like 'pantheon-solr' is hard-coded for the form action on solr-options-page.php but not in the function add_options_page on the main file. This causes a permissions error which is quickly fixable.

**Comment by allan23** [comment]
@joshkoenig Can this issue be closed?

**Comment by joshkoenig** [comment]
Indeed!
