### ISSUE TITLE
Submit schema is not working in kalabox site

### ISSUE THREAD

**Issue by gtenaschuk** [pantheon-systems/solr-power#231]
I created a local site in kalabox and when i try to activate the plugin it is showing an error message 

> Submitting the schema failed with the message Schema Upload Error: 204

**Comment by danielbachhuber** [comment]
Related #230

I think submitting a schema only works on Pantheon right now.

**Comment by gtenaschuk** [comment]
I already did it @ataylorme, i have a symbolic link called `uploads` that points to the `files` folder created by kalabox and inside it i have the _`solr-for-wordpress-on-pantheon/schema.xml`_

**Comment by danielbachhuber** [comment]
@gtenaschuk Did you get this worked out?
