### ISSUE TITLE
Port # not displaying on SOLR Options > Info page

### ISSUE THREAD

**Issue by michaelwdc** [pantheon-systems/solr-power#235]
This is on a non-Pantheon site (I'd love to put them on Pantheon, but they have their own hosting).

Its an easy fix.  On line 23 of views/options/info.php, change:

`<td><?php echo esc_html( getenv( $server_info['port'] ) ); ?></td>`

TO

`<td><?php echo esc_html( $server_info['port'] ); ?></td>`

**Comment by ataylorme** [comment]
Hi @michaelwdc,
This was actually fixed in a [commit earlier today](https://github.com/pantheon-systems/solr-power/commit/d619b36d9d4c234bdddc1cb296cb1e15e69702aa).

Thanks to @gtenaschuk for catching it in the initial PR #233 

It will ship out in our next version update to WordPress.org.
