### ISSUE TITLE
400 Error when reposting schema.xml

### ISSUE THREAD

**Issue by mindofjonas** [pantheon-systems/solr-power#239]
When attempting to repost a custom schema via the plugin options, the plugin returns the error **Schema Upload Error: 400**.

Environment: WordPress 4.7.3 running on PHP 5.5.5 on Pantheon Multi-dev.

**Comment by joshkoenig** [comment]
We have some additional info in an internal ticket. I'll try to get relevant information surfaced here. We just released plugin version `1.1.0` but if we can reproduce this we should consider prioritizing a `1.1.1` bugfix release.

**Comment by joshkoenig** [comment]
#### Steps To Reproduce:

1. Spin up WP 4.7.3 site
2. Enable Solr add-on
3. Enable Solr Power plugin
4. Push custom schema.xml to wp-content/uploads/solr-for-wordpress-on-pantheon dir
5. In WP site at Solr Options, attempt to repost schema.xml
6. Get error state, see screen capture: https://www.screencast.com/t/DBGFfwtC

**Comment by joshkoenig** [comment]
@mindofjonas - would you be comfortable sharing your custom schema so we can review that?

**Comment by mindofjonas** [comment]
@joshkoenig It was a simple test so it's the same default schema.xml included in the plugin with the `post_author` field commented out.

**Comment by joshkoenig** [comment]
Ok thanks! We should be able to reproduce that.

**Comment by danielbachhuber** [comment]
@mindofjonas In your test, did you remove this attribute from the `schema.xml` too (bottom of the file)?

![image](https://cloud.githubusercontent.com/assets/36432/24929014/58f1e316-1eb9-11e7-8184-f78aba2d92d3.png)

If I remove `<field name="post_author" type="string" indexed="true" stored="true"/>` and leave `<copyField source="post_author" dest="spell"/>`, then I see a 400 when I try to submit the custom schema.

If I remove the `<copyField source="post_author" dest="spell"/>` in addition to the `post_author` field, then I see a 200 when I submit the custom schema.

In any case, we should make sure the error message is more descriptive.

**Comment by danielbachhuber** [comment]
> In any case, we should make sure the error message is more descriptive.

For the error I saw, the actual Solr response is:

```
<h1>HTTP Status 400 - Error executing default implementation of CREATE</h1>
<hr size="1" noshade="noshade">
<p><b>type</b> Status report</p>
<p><b>message</b> <u>Error executing default implementation of CREATE</u></p>
<p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p>
```

Maybe not the most helpful error message, but Googleable at least, I suppose.

**Comment by mindofjonas** [comment]
Thanks, that was the source of the issue. It'd definitely be helpful if the plugin surfaced the full error for troubleshooting as in cases like this.
