### ISSUE TITLE
WP Query ignores post_type query_var

### ISSUE THREAD

**Issue by mindofjonas** [pantheon-systems/solr-power#244]
When using the plugin with the default WordPress query it ignores restricting results by post_type. I've tested this on the WordPress search page using `?s=my-term&post_type=my-post-type`. Regardless of the post type set the query returns all post types.

**Comment by danielbachhuber** [comment]
Thanks for the report, @mindofjonas. We'll take a look, and follow up when we know more.

**Comment by danielbachhuber** [comment]
@mindofjonas Can you apply the change in #246 and verify it fixes your issue?

**Comment by mindofjonas** [comment]
Thanks that fixed it.

**Comment by danielbachhuber** [comment]
@mindofjonas Great! This fix will go out in 1.2.0 with multisite support, hopefully in the next couple of weeks. Feel free to apply the change to your copy of the plugin as an interim fix.
