### ISSUE TITLE
BBPress bbp_has_topics() and bbp_has_replies() returning false

### ISSUE THREAD

**Issue by mindofjonas** [pantheon-systems/solr-power#245]
In bbPress 2.5+ with WordPress 4.0+ the `bbp_has_topics` and `bbp_has_replies` functions assume that is_search() is true and that `s` is always set as part of the query. However, when using with the Solr Power plugin there are occasions where `s` is false or empty - causing no topics/replies to be returned. 

An example is available [here](https://bbpress.org/forums/topic/bbp_has_topics-not-working-properly-on-my-theme/) with a bbPress specific fix [here](http://www.rewweb.co.uk/bbpress-wp4-fix/). 

Ideally Solr Power should check whether `s` is set/not empty when building a query and if not unset it.

**Comment by danielbachhuber** [comment]
@mindofjonas Just to clarify, are you working with BuddyPress or bbPress? The links you've included are to bbPress threads.

**Comment by danielbachhuber** [comment]
I *think* this is what you're referring to:

![image](https://cloud.githubusercontent.com/assets/36432/25101268/6c856b88-2368-11e7-8e30-7fbbe38d97b5.png)

If so, it also should be addressed by #246

**Comment by mindofjonas** [comment]
@danielbachhuber thanks for catching that. The issue is tied to bbPress and I've updated the issue with the correct information. #246 causes `bbp_has_topics` and `bbp_has_replies` to return all posts - not just forum posts.

**Comment by mindofjonas** [comment]
However applying #246 along with the [fix mentioned above](http://www.rewweb.co.uk/bbpress-wp4-fix/) solves the issue.

**Comment by ataylorme** [comment]
> However applying #246 along with the fix mentioned above solves the issue.

Thanks for the update @mindofjonas - going to close this out since #246 was merged and will go out in the next release

**Comment by mindofjonas** [comment]
A follow up to this in case someone else runs into this issue. After testing Solr Power with a large BBPress site (12,000+ replies/posts) I noticed major slow downs on the individual forum and topic pages.

The solution is to set `s` to **NULL** in the query args for `bbp_has_topics` and `bbp_has_replies` via either a filter or within the template files (see below).
```
if ( bbp_has_topics( array( 's' => NULL ) ) {
   // continue
}

// or

if ( bbp_has_replies( array( 's'=> NULL ) ) {
   // continue
}
```
