### ISSUE TITLE
Searching by author name?

### ISSUE THREAD

**Issue by mindofjonas** [pantheon-systems/solr-power#248]
How would I implement a search for posts by author name using Solr Power? When using a default WP Query like`s=author-name` it will return both posts by that post_author and posts where the author's name appears in the post_title/post_content. However Solr Power returns only the later.

**Comment by ataylorme** [comment]
> However Solr Power returns only the later.

@mindofjonas are you not seeing the results at all or are they lower in the search results?

Solr Power boosts `post_title` and `post_content`. See [`includes/class-solrpower-api.php`](https://github.com/pantheon-systems/solr-power/blob/master/includes/class-solrpower-api.php#L355:L365). 

The boosted items are filterable via [`solr_boost_query`](https://github.com/pantheon-systems/solr-power/wiki/Filters#solr_boost_query).

`WP_Query` with Solr also has support for `post_author` as a parameter, rather than including it in the search. 

Author is also a facet available to the facet search widget.

**Comment by mindofjonas** [comment]
@ataylorme it returns only posts where the author's name is explicitly included in the title or content.

I've tried using the boost filter as below but that doesn't return results by an author. 
```
function wlw_solr_query( $dismax, $query ){
    $dismax->setQueryFields('post_author^2.5 post_title^2 post_content^1.5');
    return $dismax;
}
add_action( 'solr_dismax_query', 'wlw_solr_query', 10, 2 );
```
We were originally using a [filter](https://danielbachhuber.com/2012/02/07/include-posts-by-matching-authors-in-your-search-results/) on `posts_search` (credit goes to @danielbachhuber) that modifies the SQL run during a search query so that a search for 'author name' would return posts by that author.

I'd like to use something similar to the above WP Query behavior instead of relying on using `post_author=author-name` or a facet on the frontend as that would add complexity to our search page.

My initial thought is to use an instance of the`SolrPower_Api` class with a modified`$qry` that also searches the `post_author` field. However I don't have experience with Solarium

**Comment by danielbachhuber** [comment]
> it returns only posts where the author's name is explicitly included in the title or content.
>
> I've tried using the boost filter as below but that doesn't return results by an author.

I was able to get this to work, without the boost filter, by modifying `schema.xml` to include:

```
<copyField source="post_author" dest="text"/>
```

See #250

> We were originally using a filter on posts_search (credit goes to @danielbachhuber) that modifies the SQL run during a search query so that a search for 'author name' would return posts by that author.

Just goes to show you can't ever outrun the code you've published on the internet ;)

**Comment by mindofjonas** [comment]
Thanks for that. I saw your note on the documentation. On a related note, might be good to add notes for the `solr_boost_query` and `solr_dismax_query` into the Wiki as well.
