### ISSUE TITLE
Search returns nothing even if there is data in solr

### ISSUE THREAD

**Issue by pmercier-ubeo** [pantheon-systems/solr-power#255]
Hi,
I'm having an query issue : 

- When I index site, I get Completed indexing in 00:00:03 elapsed time (20 indexed, 0 failed) and I have values in Solr but I get everything at 0 in **Indexing Stats by Post Type** 
- When I try a query, I get empty result. When I remove 'solr_integrate' => true, the query is ok and returns results.

So it is like if the plugin can push data but cannot retrieve it.

**Comment by ataylorme** [comment]
Hi @pmercier-ubeo,
Are you using a custom post type or the standard WordPress `post`?

Also if you can provide your full `WP_Query` arguments that would be helpful.

Which version of the plugin are you using?

**Comment by pmercier-ubeo** [comment]
Yes, but I tried with pages and posts. I get this error : RequestHandlerBase
org.apache.solr.common.SolrException: can not use FieldCache on multivalued field: post_title

**Comment by pmercier-ubeo** [comment]
Here is the request : 
`$args = array(
				'post_type'   => 'vdp_maladies',
				'post_status' => 'publish',
				'orderby'     => 'title',
				'order'       => 'ASC',
				'posts_per_page' => -1,
				'solr_integrate' => true
			);

$Query= new WP_Query($args);`

**Comment by ataylorme** [comment]
> Yes I use custom post type and I use 1.2.0. I get this error : RequestHandlerBase
org.apache.solr.common.SolrException: can not use FieldCache on multivalued field: post_title

Great, you are on the latest version! I'm not sure about the error message. I'll do some more research tomorrow. Are you using a custom `schema.xml`?

Is your post type `vdp_maladies` public? Solr Power will only index public post types by default. If it isn't public (and searchable) you can use the [`solr_post_types` filter](https://github.com/pantheon-systems/solr-power/wiki/Filters#solr_post_types)

Also try limiting the `posts_per_page`, negative one can cause issues as your number of post sgrows. Maybe `100`?

**Comment by pmercier-ubeo** [comment]
Hi, I'm not using a custom schema.xml.
Yes, post type is public and data is indexed in Solr.
I change the limit to 20, same empty result.

Thanks !

**Comment by ataylorme** [comment]
Are you running Solr on Pantheon or elsewhere? If somewhere else what version of Solr?

**Comment by pmercier-ubeo** [comment]
Elsewhere, V 6.5

**Comment by gtenaschuk** [comment]
@pmercier-ubeo 
I'm not sure about that error message but, as you are not using `s` parameter in your query, empty results could be related with this line https://github.com/pantheon-systems/solr-power/blob/master/includes/class-solrpower-wp-query.php#L332

Could you try adding a `s` attribute in your query and check if it works that way?

**Comment by pmercier-ubeo** [comment]
I added a "s" attribute, still no results.

**Comment by pmercier-ubeo** [comment]
Hi, any updates on this ? I can use Solarium directly without problem, but WP plugin does not seem to find data even if it is able to save it to solr.

**Comment by ataylorme** [comment]
Hi @pmercier-ubeo,
Solr Power is tested on Solr `3.6`, which uses the `schema.xml` file. My guess is the configuration there isn't being applied as newer versions of Solr use a [schema API](https://cwiki.apache.org/confluence/display/solr/Schema+API).

We don't have access to an infrastructure with Solr `6.5` so cannot test. If you would like to submit the schema configuration via the API you may have success. We'd be happy to have a pull request if you get things working on Solr `6.5`

**Comment by Japhys** [comment]
Having the same issue. Clean LAMP, Solr and WP install. Everything installs and works fine. Data is being indexed. No search results though. Might try it on 3.6. Hopefully this will work on 6.5 as well soon.

**Comment by danielbachhuber** [comment]
Hey @pmercier-ubeo @Japhys

We're only supporting Solr 3.6 for the foreseeable future, which is available as turnkey infrastructure on Pantheon.
