### ISSUE TITLE
Media Library search fails in "grid view" with solr-power enabled

### ISSUE THREAD

**Issue by gabehammersmith** [pantheon-systems/solr-power#284]
Steps to reproduce: 

1. Add media, enable solr-power, create index
1. Search for a known string existing in the media library in the default "grid" view 

Expected outcome: 
- Results returned

Actual outcome: 
- "No media files found."

Workarounds: 
- Clicking the "list view" icon returns the expected results.

**Comment by danielbachhuber** [comment]
Thanks for the report, @gabehammersmith!

Out of curiosity, would you expect Solr Power to override media library queries when enabled, or no?

**Comment by gabehammersmith** [comment]
@danielbachhuber - Interesting question. I believe a compelling case could be made for either option. 

I've never installed Solr to solve a media library query problem, so I think my answer would be that I view the override as a (potentially positive) side effect.

**Comment by danielbachhuber** [comment]
Thanks @gabehammersmith 

@ataylorme I've been able to reproduce this bug, and tracked it down to cbb6b1daa9430419751df5a6d6704ccefdba9af2

When `DOING_AJAX`, `is_admin()` is always true, so the current set of conditionals in the `setup()` method is buggy. Solr is always used for admin ajax requests. My apologies for not spotting this sooner.

I think we need to revert that changeset, and some of the logic in #216, and either:

1. Continue to use admin ajax for the search widget requests, but have the search widget opt itself into using Solr.
2. Switch the search widget to use a custom REST API endpoint (which is technically more appropriate, I think), but would require bumping minimum supported version to WP 4.4.

**Comment by ataylorme** [comment]
@danielbachhuber I personally favor the second option as it's cleaner than using admin ajax on the front end.

@joshkoenig do you have an objection to bumping the WordPress minimum supported version up to `4.4` and above?

**Comment by ataylorme** [comment]
@joshkoenig bump - related to #285. Can you weigh in on using the REST API and bumping the minimum version to `4.4`?

**Comment by joshkoenig** [comment]
+1 for this. We don't have a huge install base and I'm more interested in supporting forward-looking users than maintaining backwards compatibility with legacy installs that aren't doing major point-release updates. ;)

**Comment by ataylorme** [comment]
@gabehammersmith can you test the fix in the `1.3` version of [Solr Power](https://wordpress.org/plugins/solr-power/)?

**Comment by gabehammersmith** [comment]
Confirmed working. Thanks all!

**Comment by ataylorme** [comment]
Great - thanks for reporting and testing @gabehammersmith
