### ISSUE TITLE
recency score

### ISSUE THREAD

**Issue by arthurCormack** [pantheon-systems/solr-power#288]
Does solr-power have the ability to make a query to solr, and adjust the rankings/score of the results based on the age/recency of posts that are indexed? ie, ranking giving newer posts a higher ranking score.

**Comment by danielbachhuber** [comment]
@arthurCormack Sorry for the late reply. Were you able to work out a solution for this?

If you haven't yet, I'd suggest looking at #272, specifically:

```
$extra['sort_before'][ "query({!dismax qf=post_title v='\"" . $query->get( 's' ) . "\"'})" ] = 'desc';
```

Using a sort query lets you boost specific results based on different attributes.
