### ISSUE TITLE
Attempt to check server status or any other action: "You do not have sufficient permissions to access this page."

### ISSUE THREAD

**Issue by michaelwdc** [pantheon-systems/solr-power#29]
I downloaded the master, added it to a WP site on Pantheon.  Trimmed off the "-master" bit from the folder (named "solr-for-wordpress"), ensured that the SOLR addon was enabled, and then activated the plugin.  Can access the settings and save changes, but cannot execute any of the actions ("Check Server Status", "Optimize Index", etc.).

**Comment by allan23** [comment]
@joshkoenig Can this issue be closed?

**Comment by joshkoenig** [comment]
Yep. This was an issue with the slug name I think. Should be all good now.
