### ISSUE TITLE
Solr Boost Query for Custom Fields

### ISSUE THREAD

**Issue by rdanamcd** [pantheon-systems/solr-power#293]
I see the filter: apply_filters( 'solr_boost_query', 'post_title^25 post_content^50' ) to change the $solr_boost_query for the main post fields.

How can I, if possible, to apply solr_boost_query to Custom Fields. Use the meta_key name? Would that work?

Thanks
Dana

**Comment by danielbachhuber** [comment]
> How can I, if possible, to apply solr_boost_query to Custom Fields. Use the meta_key name? Would that work?

This seems like it should work, unless it's not something Solr supports.

Meta keys are registered using dynamic fields. For a meta field of 'price', the name would be `price_str`
