### ISSUE TITLE
Issue with orderby = meta_value_num

### ISSUE THREAD

**Issue by rdanamcd** [pantheon-systems/solr-power#298]
Ordering the results by meta_value_num does not work for me when using Solr.

Example query:
$query_args = array( 'orderby'=>'meta_value_num', 'meta_key'=>'custom_number_field');

Everything is fine until function parse_orderby(...) in class-solrpower-wp-query.php line 272. On line 339 in the switch( $orderby ) case 'meta_value_num' it sets the $orderby_clause to "{$primary_meta_query['alias']}_i}. Unfortunately the "alias" is always = "wp_postmeta". So $orderby_clause then = "wp_postmeta_i" which is incorrect.

I changed line 340 from $orderby_clause = "{$primary_meta_query['alias']}_i"; to: $orderby_clause = "{$primary_meta_query['key']}_i"; and it works perfectly.

Is there anything I'm missing? Should line 340 use 'alias'? Unfortunately there were no Filters to update the $orderby_clause before it is used so I had to update the code directly.

Please consider changing line 340 to described as above.

Thanks
Dana

**Comment by danielbachhuber** [comment]
Thanks for the report, @rdanamcd.

> Is there anything I'm missing? Should line 340 use 'alias'?

It looks like the change came in a massive changeset, so it's hard to say what the original intent might be: 1671472370e250c371818109750db3bf8b8b1a19

I added a test case to reproduce the failure in d7826b93da49cb237d84879eb74cb5550a3b30ec

The change you suggest doesn't seem to pass the test though:

![image](https://user-images.githubusercontent.com/36432/28029411-d6abfa94-6554-11e7-8aab-aba639a7814e.png)

Looking into this further...

**Comment by danielbachhuber** [comment]
> The change you suggest doesn't seem to pass the test though:

Test case was buggy :) 985dff4e4c829db3eb726dc0756e11ddb9653924
