### ISSUE TITLE
Solr Power conflicts with ACF Pro post object fields in admin

### ISSUE THREAD

**Issue by mindofjonas** [pantheon-systems/solr-power#301]
When using Solr Power with Advanced Custom Fields' post object field - all results are not being returned despite there being matching post objects to show. Since ACF's post object field uses AJAX to power its UI, I've tested using the `solr_allow_ajax` filter on it's query without success.

**Comment by danielbachhuber** [comment]
Hi @mindofjonas,

To confirm, are you using Solr Power v1.3.0?

**Comment by mindofjonas** [comment]
I was using Solr Power v1.2.0. Updating to v1.3.0 seems to have fixed it

**Comment by danielbachhuber** [comment]
> Updating to v1.3.0 seems to have fixed it

Great! The actual fix was #295
