### ISSUE TITLE
Widget Error when pressing "Reset"

### ISSUE THREAD

**Issue by eabquina** [pantheon-systems/solr-power#305]
Facet is placed in the homepage with all the filters already placed: 
A reset button appears with a link and url that seems to be giving out an error

`Warning: htmlspecialchars_decode() expects parameter 1 to be string, array given in /srv/bindings/f05e4ae0e26944f29b76410c974d5f49/code/wp-content/plugins/solr-power/includes/class-solrpower-wp-query.php on line 421`

http://dev-impactevals.pantheonsite.io/?&facet%5Bpost_author%5D%5B%EF%BF%BD*%EF%BF%BDvalues%5D%5Bjosephine%5D=10&facet%5Bpost_author%5D%5B%EF%BF%BD*%EF%BF%BDvalues%5D%5Blisa%5D=5&facet%5Bpost_author%5D%5B%EF%BF%BD*%EF%BF%BDvalues%5D%5Blcwebb%5D=2&facet%5Bpost_type%5D%5B%EF%BF%BD*%EF%BF%BDvalues%5D%5Bpost%5D=16&facet%5Bpost_type%5D%5B%EF%BF%BD*%EF%BF%BDvalues%5D%5Bpage%5D=1

**Comment by danielbachhuber** [comment]
Thanks for the report, @eabquina. Cleaning up the query string, here's what I see:

```
$ wp shell
wp> rawurldecode( '&facet%5Bpost_author%5D%5B%EF%BF%BD*%EF%BF%BDvalues%5D%5Bjosephine%5D=10&facet%5Bpost_author%5D%5B%EF%BF%BD*%EF%BF%BDvalues%5D%5Blisa%5D=5&facet%5Bpost_author%5D%5B%EF%BF%BD*%EF%BF%BDvalues%5D%5Blcwebb%5D=2&facet%5Bpost_type%5D%5B%EF%BF%BD*%EF%BF%BDvalues%5D%5Bpost%5D=16&facet%5Bpost_type%5D%5B%EF%BF%BD*%EF%BF%BDvalues%5D%5Bpage%5D=1' );
=> string(215) "&facet[post_author][�*�values][josephine]=10&facet[post_author][�*�values][lisa]=5&facet[post_author][�*�values][lcwebb]=2&facet[post_type][�*�values][post]=16&facet[post_type][�*�values][page]=1"
```

I tried to reproduce by:

### 1. Creating two test posts assigned to two different test users

![image](https://user-images.githubusercontent.com/36432/28718404-970008a4-735a-11e7-8211-0022edf4792d.png)

### 2. Searching for "Testing" and faceting to both authors.

![image](https://user-images.githubusercontent.com/36432/28718410-a851465e-735a-11e7-88d2-99689efc8d8f.png)

### Results

I ended up with a URL like this:

```
?s=testing&paged=1&facet%5Bpost_author%5D%5B%5D=Test+Author&facet%5Bpost_author%5D%5B%5D=editor
```

Notably, the structure of the query string is a bit different:

```
wp> rawurldecode( 's=testing&paged=1&facet%5Bpost_author%5D%5B%5D=Test+Author&facet%5Bpost_author%5D%5B%5D=editor' );
=> string(78) "s=testing&paged=1&facet[post_author][]=Test+Author&facet[post_author][]=editor"
```

See `facet[post_author][]=Test+Author` in this case vs. `&facet[post_author][�*�values][josephine]=10` in your case.

---

> Facet is placed in the homepage with all the filters already placed:

Can you share more information about your configuration, with sufficient detail to reproduce? Thanks.
