### ISSUE TITLE
doubling up on facet search parameters leads to invalid options data state

### ISSUE THREAD

**Issue by tmulry** [pantheon-systems/solr-power#306]
I am able to put the plugin into an invalid state by putting the same facet word twice in the "Custom fields as Facet " field
1. goto plugin settings -> Facet Options
1. enable 'taxonomy as facet' and enter "status,status" in the Custom fields as Facet field.  
1. save changes

The settings Page loads with a stack trace in the stats section.  I needed to clear out the `plugin_s4wp_settings` option data in the DB to get the settings page working again.   
`Fatal error: Uncaught Solarium\Exception\InvalidArgumentException: A facet must have a unique key value within a query in /srv/bindings/9a0354892893416aaf9873d4576d802e/code/wp-content/plugins/solr-power/vendor/solarium/solarium/library/Solarium/QueryType/Select/Query/Component/FacetSet.php:374 Stack trace: #0 /srv/bindings/9a0354892893416aaf9873d4576d802e/code/wp-content/plugins/solr-power/vendor/solarium/solarium/library/Solarium/QueryType/Select/Query/Component/FacetSet.php(513): Solarium\QueryType\Select\Query\Component\FacetSet->addFacet(Object(Solarium\QueryType\Select\Query\Component\Facet\Field)) #1 /srv/bindings/9a0354892893416aaf9873d4576d802e/code/wp-content/plugins/solr-power/vendor/solarium/solarium/library/Solarium/QueryType/Select/Query/Component/FacetSet.php(529): Solarium\QueryType\Select\Query\Component\FacetSet->createFacet('field', 'status_str', true) #2 /srv/bindings/9a0354892893416aaf9873d4576d802e/code/wp-content/plugins/solr-power/includes/class-solrpower-api.php(393): Solarium\QueryType\Select\Que in /srv/bindings/9a0354892893416aaf9873d4576d802e/code/wp-content/plugins/solr-power/vendor/solarium/solarium/library/Solarium/QueryType/Select/Query/Component/FacetSet.php on line 374`

**Comment by danielbachhuber** [comment]
Thanks for the report, @tmulry. Fixing this up in #309
