### ISSUE TITLE
Multisite: Wrong menu highlighted after running an action

### ISSUE THREAD

**Issue by ocean90** [pantheon-systems/solr-power#317]
After clicking an action button on `/wp-admin/network/admin.php?page=solr-power#top#solr_action` you get redirected to `/wp-admin/network/settings.php?page=solr-power#top#solr_action` and the "Settings" menu is highlighted.

<img width="426" alt="solr" src="https://user-images.githubusercontent.com/617637/29613749-b812abc0-8807-11e7-99ac-454cdb884b17.png">

**Comment by danielbachhuber** [comment]
Thanks for the report @ocean90. We'll get this fixed.
