### ISSUE TITLE
Single quote ' breaks search

### ISSUE THREAD

**Issue by JamesJosephFinn** [pantheon-systems/solr-power#322]
A search which includes a single quote ' character (as you would use in possession, for example) returns null.

https://www.cloudchemistry.co/?s=Dragon%27s+breath

**Comment by JamesJosephFinn** [comment]
Furthermore, searching for "dragons breath" without the single quote returns the exact match result mid-page:

https://www.cloudchemistry.co/?s=Dragons+breath

**Comment by ataylorme** [comment]
Thanks for the report @JamesJosephFinn - we'll try to reproduce and see if we can find the source of the issue.
