### ISSUE TITLE
WP User Query

### ISSUE THREAD

**Issue by rdanamcd** [pantheon-systems/solr-power#323]
Any future plans to solr_integrate on the WP User Query?

Just curious.

Thanks
Dana

**Comment by danielbachhuber** [comment]
> Any future plans to solr_integrate on the WP User Query?

No plans at this time. Given a user schema would be quite different than a post schema, I think it would be somewhat difficult to reconcile the two.

If you need to search users with faceting, one approach would be to create a hidden "User" CPT that mirrors user data.
