### ISSUE TITLE
Searching for Negative Values in Meta Query

### ISSUE THREAD

**Issue by rdanamcd** [pantheon-systems/solr-power#324]
I have a meta_query that is working fine with solr_integrate=false but does not work with solr_integrate=true.

I did some digging and found what I think may be the issue. My meta_query is as follows:
`'meta_query' => array(
	array(
		'key'	=> ‘meta_key_name’, 
		'value'	=> 1,				
		'type'	=> 'numeric',
		'compare' => '!='
	),
	array(…)	
)`

This issue is I have a lot of records with the "meta_key_name" value set as -1. All the -1 values should be found, but searching with Solr, they were Not found.

I found in class-solrpower-wp-query.php in the function "set_query_value( ... )":
`	private function set_query_value( $value, $type = null ) {

		if ( '*' === $value ) {
			return $value;
		}

		switch ( $type ) {
			case 'd':
				return floatval( $value );
				break;
			case 'i':
				return absint( $value );
				break;
			default:
				return '"' . $value . '"';
				break;
		}

	}
`
The case "i" returns an AbsoluteInteger. Is this by design? It's converting all my negative integers to positive ones making the search invalid. Should absint($value) be intval($value)? Is there another way to Search for Negative Integers?

Thanks
Dana

**Comment by danielbachhuber** [comment]
> The case "i" returns an AbsoluteInteger. Is this by design?

It's hard to say from the original commit :( 1671472370e250c371818109750db3bf8b8b1a19

> t's converting all my negative integers to positive ones making the search invalid. Should absint($value)` be intval($value)? Is there another way to Search for Negative Integers?

This seems like a reasonable assumption to me.
