### ISSUE TITLE
Exception during suggester query

### ISSUE THREAD

**Issue by aayler** [pantheon-systems/solr-power#329]
Hello,

We're trying to implement the Suggester query by following the sample included in `suggester-query.md`.

Our method =
```
function rest_suggest( WP_REST_Request $request ) {
      $q = stripslashes( $request['s'] );
      $results = array();
      $client = SolrPower_Api::get_instance()->get_solr();

      $query = $client->createSuggester();
      $query->setQuery( $q );
      $query->setDictionary( 'suggest' );
      $query->setOnlyMorePopular( true );
      $query->setCount( 5 );
      $query->setCollate( true );

      $results = $client->suggester( $query );
      ...
```
However, an exception is thrown = 
```
Solarium\Exception\HttpException: Solr HTTP error: OK (404)
HTTP Status 404 - /sites/self/environments/kalabox/index/suggest
The requested resource is not available. 
in /code/wp-content/plugins/solr-power/vendor/solarium/solarium/library/Solarium/Core/Query/Result/Result.php on line 106
```

Any suggestions?

**Comment by danielbachhuber** [comment]
Hi @aayler,

Thanks for taking the time to file a report.

> We're trying to implement the Suggester query by following the sample included in `suggester-query.md`

Where is this document? I'm not sure exactly where this is.

> Any suggestions?

`<rimshot />`

I'm not 100% sure suggestions are available in Solr v3.6, which is what Pantheon is running. The exception indicates it's hitting a 404, which would mean the endpoint isn't responding.

Can you share more detail about your path to this point?

**Comment by aayler** [comment]
Hi @danielbachhuber,

I appreciate your note, thanks for taking the time to review this.

The .md file was bundled in the solr-power vendor folder = `solarium/docs/queries/` (also https://solarium.readthedocs.io/en/stable/queries/suggester-query/)

It seems the Suggester class is available for Solr 3.6.1 (https://lucene.apache.org/solr/3_6_1/org/apache/solr/spelling/suggest/Suggester.html) -- is this the current version on Pantheon?

As for our implementation, we created a search class with the constructor:

private function __construct() {
      if ( class_exists( 'SolrPower_Sync' ) ) {
        if ( function_exists( 'register_rest_route' ) ) {
          add_action( 'rest_api_init', function() {
            register_rest_route( 'website/v1', '/suggest', array(
              'methods' => 'GET',
              'callback' => array( $this, 'rest_suggest' ),
            ) );
          } );
        }
...
}

The callback is the method in the original post ...

Thanks!

**Comment by aayler** [comment]
The call stack at exception:
```
   2.3774   17407712  14. Website_Search->rest_suggest() /code/wp-includes/rest-api/class-wp-rest-server.php:927
    2.3782   17424960  15. Solarium\Core\Client\Client->suggester() /code/wp-content/themes/website/inc/class-website-search.php:168
    2.3782   17425008  16. Solarium\Core\Client\Client->execute() /code/wp-content/plugins/solr-power/vendor/solarium/solarium/library/Solarium/Core/Client/Client.php:964
    2.3830   17431952  17. Solarium\Core\Client\Client->createResult() /code/wp-content/plugins/solr-power/vendor/solarium/solarium/library/Solarium/Core/Client/Client.php:774
    2.3833   17446136  18. Solarium\Core\Query\Result\Result->__construct() /code/wp-content/plugins/solr-power/vendor/solarium/solarium/library/Solarium/Core/Client/Client.php:742
```

**Comment by aayler** [comment]
In Solr 6.6 (https://lucene.apache.org/solr/guide/6_6/suggester.html), apparently, there are configurations to `solrconfig.xml` that are necessary for the suggest functionality. Could it be that, Pantheon, running 3.6, and without user access to `solrconfig.xml` does not support this?

**Comment by danielbachhuber** [comment]
> Could it be that, Pantheon, running 3.6, and without user access to `solrconfig.xml` does not support this?

Good find. I don't know personally, so I'll ping internally.

**Comment by danielbachhuber** [comment]
@aayler The person I pinged didn't know off the top of his head.

I tried your code on a test Pantheon site and received the same error:

![image](https://user-images.githubusercontent.com/36432/31312382-691e72aa-ab8f-11e7-908a-45123c9e55d8.png)

Here's my test code:

```
<?php

if ( empty( $_GET['test_suggest'] ) ) {
	return;
}

add_action( 'template_redirect', function() {
	$q = stripslashes( $_GET['test_suggest'] );
	$results = array();
	$client = SolrPower_Api::get_instance()->get_solr();

	$query = $client->createSuggester();
	$query->setQuery( $q );
	$query->setDictionary( 'suggest' );
	$query->setOnlyMorePopular( true );
	$query->setCount( 5 );
	$query->setCollate( true );

	$results = $client->suggester( $query );
	var_dump( $results );
	exit;
});
```

I've opened a support ticket to route the question to the proper person, and requested they weigh in with greater detail on this issue. Feel free to open a ticket of your own too, if you'd like to include additional background on the project you're working on.

**Comment by danielbachhuber** [comment]
I've heard back from support, who confirmed that the Suggester component isn't available. He suggested considering an external Solr provider (e.g.  IndexDepot, Opensolr, GotoSolr) if it's a requirement for your project.

**Comment by aayler** [comment]
thanks @danielbachhuber, i really appreciate your taking the time to follow up. will review your suggestions.

thanks again!
