### ISSUE TITLE
Configurability for search order?

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/solr-power#33]
Right now the defauly search query will still return posts sorted by created order. I think the default should be to sort them by their relevance (score). It would make for a pretty nifty demo:

- **Before**: Here are your Vanilla search results in date posted. (sad trombone)
- **After**: Behold! Solr Powered search results, which pulled an older post to the top because it's clearly more relevant. (gong!)

**Comment by joshkoenig** [comment]
This is pretty easy to do by hard-coding in `posts_request`. However, I'm not sure this is the most sustainable and "correct" way to proceed. 

I'm going to make the change now in the name of getting an initial beta release up and running. However, I would like to explore our options for providing a more robust developer interface (and ultimately user interface) for the search experience.

**Comment by allan23** [comment]
Could implement a filter with the default being score. After that, there could be a setting on the options page to set the default.
