### ISSUE TITLE
Docker Install Available

### ISSUE THREAD

**Issue by kshaner** [pantheon-systems/solr-power#330]
For anyone that is working with Docker or wants a simpler way to work with a solr index (especially on Windows) that will eventually go up on Pantheon, I've made a simple docker container to get you up and running locally based the bash script in this repo.

https://hub.docker.com/r/kshaner/solr/

Hopefully this helps anyone.

**Comment by ataylorme** [comment]
This looks great, thanks for sharing @kshaner!

You might also want to take a look at [the Solr Docker image Kalabox maintains](https://hub.docker.com/r/kalabox/pantheon-solr/).

They have images for our app servers as well if you want to run everything in Docker.

**Comment by danielbachhuber** [comment]
These would be great for the README :) #331
