### ISSUE TITLE
Ability to Specify Custom Taxonomies to Index

### ISSUE THREAD

**Issue by DaveyJake** [pantheon-systems/solr-power#334]
While there is the option to index custom fields, I do not see a mean to index custom taxonomies.  If there something I'm overlooking or is this feature not yet available?

**Comment by danielbachhuber** [comment]
Hi @DaveyJake,

All custom taxonomies are indexed by default. Custom fields require admin UI because the user needs to opt-in to which fields should be indexed (because some fields may have private data). Taxonomies have a better permissions system and can be indexed by default.

Is there some issue you're running into that I can help debug?

**Comment by DaveyJake** [comment]
Hi @danielbachhuber,

For displaying widget facets, I only need to 3 taxonomies and their children displaying in the same manner as `Categories` and `Tags` are when enabled.  Is there a `filter` of some kind that I can utilize in my theme?  I did not see one available pertaining to custom taxonomies on the <a href="https://github.com/pantheon-systems/solr-power/wiki">`Solr Filters Wiki`</a> page.

This feature is really all I'm missing to finish the search functionality for my current project.

**Comment by danielbachhuber** [comment]
> For displaying widget facets, I only need to 3 taxonomies and their children displaying in the same manner as Categories and Tags are when enabled.

What happens when you check the "Taxonomy as Facet" option in "Facet Options"?

![image](https://user-images.githubusercontent.com/36432/31466700-027dbb72-ae8d-11e7-912f-a1b8580483cd.png)

**Comment by DaveyJake** [comment]
Here are my settings:

<img width="524" alt="screen shot 2017-10-11 at 6 10 56 pm" src="https://user-images.githubusercontent.com/826532/31473165-02306bb0-aeb0-11e7-8bf4-d4f2748de813.png">

Here is what I get on the front-end:

<img width="268" alt="screen shot 2017-10-11 at 6 10 22 pm" src="https://user-images.githubusercontent.com/826532/31473174-0e499ffc-aeb0-11e7-87cb-35b5501fbb21.png">

Additionally, it should be noted that the client has made it explicitly clear that he **does not** want to use only the `Categories` taxonomy for his posts as his website is sports-centered and revolving players, performances, matches, etc.  He prefers to have multiple `post_types` within any given taxonomy should it be fit to the content he and his people produce.

**Comment by danielbachhuber** [comment]
@DaveyJake I'm not sure I fully understand what you expect out of Solr Power.

My understanding is that you currently see the Categories and Tags taxonomies appearing in your faceting widget. You _expect_ to also see the custom taxonomies you've registered.

Is this a correct understanding? If it is, can you share the code you've used to register your custom taxonomies?

If my understanding isn't correct, can you share in greater detail what you're trying to do, and how you expect Solr Power to accommodate it?

**Comment by DaveyJake** [comment]
You are correct: **I do expect to also see the custom taxonomies I've registered--all of which are publicly _queryable_.**

The custom taxonomies that I have registered are `Gender`, `Division` and `Region`.

Here's a mock-up of what I want to see.

<img width="354" alt="screen shot 2017-10-11 at 9 54 09 pm" src="https://user-images.githubusercontent.com/826532/31478658-33f2b620-aecf-11e7-9cb4-ab445b521ef2.png">

I hope this clears things up a bit? If there's any confusion please let me know.

**Comment by danielbachhuber** [comment]
> I hope this clears things up a bit? If there's any confusion please let me know.

Yep, I was able to reproduce the issue. I've identified a fix in #335
