### ISSUE TITLE
Add support for SOLR SpellCheck Module

### ISSUE THREAD

**Issue by JamesJosephFinn** [pantheon-systems/solr-power#337]
Feature request: Please integrate support for SOLR SpellCheck.

**Comment by danielbachhuber** [comment]
Hi @JamesJosephFinn,

Thanks for the suggestion. Could you explain in greater detail how you'd expect it to be integrated?

**Comment by JamesJosephFinn** [comment]
HI Daniel,

Currently I have the plugin running on [my Pantheon site](https://www.cloudchemistry.co/). Any [search that contains a misspelling](https://www.cloudchemistry.co/?s=bluebery) returns null. I can't say I know from experience, but I was just assuming you don't have the SpellCheck module running because of this.

**Comment by danielbachhuber** [comment]
Cool, thanks for the additional detail. I'll flag this issue for support — this issue tracker is for Solr Power specifically, not necessarily Pantheon's Solr configuration.

**Comment by JamesJosephFinn** [comment]
Hi @danielbachhuber, was this module implemented in Pantheon's SOLR provisioning? Thanks!

**Comment by danielbachhuber** [comment]
It was not, and there aren't any plans to do so.

**Comment by JamesJosephFinn** [comment]
That's surprising. SOLR on Pantheon is a paid feature, and it seems a basic search function to return results even if the query isn't an exact match. Thanks for your consideration.
