### ISSUE TITLE
Displaydate sort option is not superseding score when selected

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/solr-power#348]
**Actual result:**

When selecting 'displaydate' as the Default Sort option, search results are still returned out of date order and appear to be sorted by score.

**Expected result:**

Search results would be in chronological order by published date.

To test:
I re-saved the indexing options, deleted the index, re-indexed the content and ran the search.
See: 
http://dev-shopeatsurf.pantheonsite.io/?s=vans
http://dev-shopeatsurf.pantheonsite.io/?s=tillys

**Comment by danielbachhuber** [comment]
Hi @ttrowell,

I'm not able to reproduce this issue locally:

![sortby](https://user-images.githubusercontent.com/36432/33689756-7892cd96-da95-11e7-9536-2a2ad245600b.gif)

In this GIF:

1. The default sort order is `score`, which means "Hello World" appears before "Sample Page"
2. "Sample Page" is published on April 18th and "Hello World" is published on April 17th.
3. Changing the sort order to `displaydate` correctly causes "Sample Page" to appear before "Hello World".

The underlying logic looks correct too:

![image](https://user-images.githubusercontent.com/36432/33689856-d7719d4c-da95-11e7-9476-3ed54ee7ca90.png)

Could we get a CSE environment for further debugging? Also, when you ask, it might be worth suggesting that there could be a plugin or some erroneous code modifying `WP_Query`, which could affect the sort order.

**Comment by tinefin** [comment]
@danielbachhuber I assume you mean a multidev? I created one on the mentioned site for you, named "pantheoncse".
