### ISSUE TITLE
Post object's post_author is saving display_name vs author id on Search Results

### ISSUE THREAD

**Issue by magbicaleman** [pantheon-systems/solr-power#353]
**Our Issue**: When search results return the post's author's avatar and display name are not displaying.

Our display code snippet (we're using blade);

```
  <a href="{{ get_author_posts_url($post->post_author) }}" rel="author" class="post-meta_author">
    <img class="post-meta_author-avatar" src="{{ get_avatar_url($post->post_author) }}" />
    <div class="post-meta_author-name">{{ get_the_author_meta('display_name', $post->post_author) }}</div>
  </a>
  | <time class="updated post-meta_time" datetime="{{ get_post_time('c', true) }}">{{ get_the_date('M j, Y') }}</time>
```

We noticed that when we deactivated `solr-power` plugin our display content started to show up, how we wanted it. Turns out that the `solr-power` plugin saves the author's display_name value in the post's post_author property, unlike by default where WordPress save the author's id in the post_author property.

We created a workaround, perhaps this breaks some optimizations. 

```php
  <?php
    /*
     * BUG FIX: When solr-power plugin is active, the post_author property is the author's
     * display name. We want to return that post_author's ID instead.
     */
    if (is_plugin_active('solr-power/solr-power.php')) :
      $post_author_by_post = get_post_field( 'post_author', $post->ID );
      $post->post_author = $post_author_by_post;
    endif;
  ?>
```

**Is there a different way, to accomplish what we want within the solr-power optimizations**?

**Comment by danielbachhuber** [comment]
Thanks for the report, @magbicaleman.

> Turns out that the solr-power plugin saves the author's `display_name` value in the post's `post_author` property, unlike by default where WordPress save the author's id in the post_author property.

I've verified this to be the case, and agree that it's less than ideal. In my opinion, the expected behavior is to have the post object remain consistent regardless of whether Solr Power is active or not.

This decision was made in 0936fb526bda87754dac801eec3dc6d7fbb6fa8d. We could potentially back out of it in some way, but there's the possibility of unexpected consequences.

@ataylorme Do you have an opinion?

**Comment by danielbachhuber** [comment]
One smaller impact option would be to keep `post_author` as the display name in the index, and only load the `post_author` ID onto the post object when `WP_Query` is filtered.
