### ISSUE TITLE
Wordpress Api doesn't work when i enable solr on wordpress(woocommerce).

### ISSUE THREAD

**Issue by eugenehub** [pantheon-systems/solr-power#360]
When i enable solr and install the plugin to my wordpress site, i cant use the wordpress api search. 

Let's say i want to find an image from the media folder called (9518.jpg), i make a search request like this: https://myWordpressSite/wp-json/wp/v2/media?search=9518 But the response i get is empty brackets [ ]. Even though the file exists in my uploads folder in the media library.

So i guess if i enable solr in woocommerce i can't use the wordpress api!

**Comment by danielbachhuber** [comment]
Hi @eugenehub,

Thanks for the report. To help us track the issue down, can you provide a bit more detail?

Specifically:

1. Did you run the full index process after activating the Solr Power plugin?
2. Do normal post search queries work as expected through the REST API?
3. What additional debugging have you done?

**Comment by eugenehub** [comment]
Hello @danielbachhuber 

1) Yes i did.
2) No. search doesn't work on media neither posts nor pages. Here is a screenshot.  
![wpapisearchdoesnotworkwithsolron](https://user-images.githubusercontent.com/16281766/37461813-641d1432-2858-11e8-9da2-af233d2d8ceb.jpg)
3) Nothing, i'm not an expert.

Thank you for your consideration!

**Comment by danielbachhuber** [comment]
Hi @eugenehub,

It's hard to say what the issue might be without being able to debug further.

If this site is on Pantheon, you can create a `cse` multidev environment and grant access to the email address on my GitHub profile so I can debug further.

If this site isn't on Pantheon, there's not much else I can do as we only offer limited support for non-Pantheon users.
