### ISSUE TITLE
Implement basic faceting widget

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/solr-power#37]
One of the best features of a Solr backend is the ability to easily "facet" the search query. We should make it easy for users to discover this power. Using the built-in categories to power a basic "Faceted Search" widget would go a long way towards this.

Other primitive facets to consider:

- Post type
- Author
- Date (month?)

**Comment by danielbachhuber** [comment]
> I'm not sure of the most "WordPress way" to do this.

Maybe a widget and an easy function to call to render the equivalent HTML.

**Comment by joshkoenig** [comment]
Another thing to consider - should we have a goal of "playing nicely" with facet-based data plugins like [FacetWP](http://facetwp.com)?

**Comment by akhillgopinath** [comment]
Hi 
Is there any way we can show the facets  in search result page ?

**Comment by ataylorme** [comment]
Facets were mentioned in the WordPress.org support forum as well ([link](https://wordpress.org/support/topic/range-facets?replies=1)).

**Comment by yumyo** [comment]
Hi,
any update on this? 

Also, +1 for "playing nicely" with FacetWP

**Comment by ataylorme** [comment]
Hi @yumyo,
This is on our radar for the next release (0.4) but we don't have a definite timeline. You can keep an eye on the [0.4 milestone](https://github.com/pantheon-systems/solr-power/milestones/0.4).

If you would like to help contribute pull requests are welcome!

**Comment by ataylorme** [comment]
Just a quick update - we released 0.4 as auto-submitting schema was a feature worthy of it's own release. Facets are still on the radar and will likely be in the next release or two.

**Comment by ataylorme** [comment]
Closed by #118

**Comment by JamesJosephFinn** [comment]
@joshkoenig you mentioned above

>playing nicely with facetWP

Was that ever woven in here? Thanks!!

**Comment by ataylorme** [comment]
facetWP support didn't make it into the search widget

**Comment by JamesJosephFinn** [comment]
Roger. Thanks.
