### ISSUE TITLE
PHP Warning due to usage of count() on integer

### ISSUE THREAD

**Issue by mgburns** [pantheon-systems/solr-power#372]
Here's the warning:

```
Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/plugins/solr-power/includes/class-solrpower-api.php on line 346
```

And here's the offending line:
https://github.com/pantheon-systems/solr-power/blob/cd3045604557b1a6bad6081249b92bd76daeeea9/includes/class-solrpower-api.php#L346

Not sure if the schema changed at some point, but as of today that option will [always be an integer](https://github.com/pantheon-systems/solr-power/blob/cd3045604557b1a6bad6081249b92bd76daeeea9/includes/class-solrpower-options.php#L207) so I think `count()` can just be removed.

**Comment by ghamok** [comment]
This also occurs for me, but only for php versions above 7.0
