### ISSUE TITLE
Upgrade to support php 7.2

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/solr-power#374]
Customer receiving this error:
`Warning: Parameter 2 to SolrPower_WP_Query::the_posts() expected to be a reference, value given in /srv/bindings/<snip>/code/wp-includes/class-wp-hook.php on line 286`

Goes away when downgrading php version to 7.0.

Internal reference:
https://pantheon-systems.desk.com/agent/case/112944

Also see #372

**Comment by danielbachhuber** [comment]
Hi @tinefin,

Have you verified the customer is running Solr Power v1.5.0? This issue should've been fixed with #342. I can't see the ticket so I don't know whether this has been discussed yet.

**Comment by danielbachhuber** [comment]
@geraldvillorente The second warning is fixed with #372

For the first warning, I'm not sure how they're still receiving that error. Can you grant me access to the site so I can look at their codebase? My Pantheon account email address is daniel@bachhuber.co
