### ISSUE TITLE
2.0 network activation on multisite on php < 7.1

### ISSUE THREAD

**Issue by kshaner** [pantheon-systems/solr-power#398]
On a multisite installation with php < 7.1, after the plugin is updated from 1.x to 2.0 (or a new installation), there is no warning that the plugin has not been activated with a network activation. The standard plugin activated admin notice appears. Took me a while to figure out what was going on because of the lack of a warning message.

I would expect the same error that appears on a single site installation to be available in the network admin:

`add_action( 'network_admin_notices', 'solr_power_php_admin_notice' );`

https://github.com/pantheon-systems/solr-power/blob/e2f133c257058beb4426e819ee5ed98e17df0c54/solr-power.php#L109

(Yes, the site in question has now been upgraded from 7.0 to 7.2)

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @kshaner. Want to submit a pull request for this?
