### ISSUE TITLE
SolrPower_Batch_Index::index_post does not include enough information to debug error

### ISSUE THREAD

**Issue by pavellishin** [pantheon-systems/solr-power#405]
[This bit tries its best to show the document title](https://github.com/pantheon-systems/solr-power/blob/60291de6ccd2148dc53dcac0e97e311956840b03/includes/class-solrpower-batch-index.php#L240-L243), but in most cases this isn't very useful:

```
$result       = $batch_index->index_post();
=> array(4) {
  ["post_id"]=>
  int(100)
  ["post_title"]=>
  string(18) "Hello I am a title"
  ["status"]=>
  string(6) "failed"
  ["message"]=>
  string(35) "Apache Tomcat/7.0.68 - Error report"
}
```

The actual body response from the server *is* useful, however:

```
<body><h1>HTTP Status 503 - Error opening new searcher. exceeded limit of maxWarmingSearchers=2, try again later.</h1>
... etc body goes on...
```

If we're regexing for `<title>`, it seems reasonable to include anything included in `<h1>` tags, too.

**Comment by danielbachhuber** [comment]
Hi @pavellishin,

It looks like this is already tracked with #397. Want to submit a pull request for it?

**Comment by pavellishin** [comment]
Oh, you're right! I should have searched before opening this.

I'll try to get something to y'all if I have time this week.
