### ISSUE TITLE
Updated wordpress.org version to 2.1

### ISSUE THREAD

**Issue by extremeshok** [pantheon-systems/solr-power#412]
Current version on https://wordpress.org/plugins/solr-power/ is 2.0

Please can this be updated to 2.1

Thank you

**Comment by ataylorme** [comment]
Hi @extremeshok,
The deployment to WordPress.org is blocked by the svn pre-commit hooks not being compatible with PHP 7.3

See https://meta.trac.wordpress.org/ticket/3791#comment:10

**Comment by danielbachhuber** [comment]
I've just asked again on the meta thread.

**Comment by danielbachhuber** [comment]
@extremeshok Sorry for the delay here. Solr Power is now at v2.1.1 on WordPress.org. I finally figured out a temporary workaround for the WordPress.org issue (documented in #419)
