### ISSUE TITLE
How to pass the custom range search on a date in solar search?

### ISSUE THREAD

**Issue by Naresh206** [pantheon-systems/solr-power#416]
Hi 

We want to do a custom range search on a date, for example, post_date from now+6 months programmatically
Another use case may be sorting the price custom field from $1000 to $2000

Can you please give an example to do this and help

**Comment by danielbachhuber** [comment]
Hi @Naresh206,

> We want to do a custom range search on a date, for example, post_date from now+6 months programmatically
> Another use case may be sorting the price custom field from $1000 to $2000

Solr Power supports most of the queries supported by `WP_Query`, so both of these should be possible.

> Can you please give an example to do this and help

Sorry, this is outside the scope of the open source support we offer.
