### ISSUE TITLE
search within comments?

### ISSUE THREAD

**Issue by jnorell** [pantheon-systems/solr-power#440]
Is there any way to customize solr-power to search within comments, just like the actual post content?

**Comment by danielbachhuber** [comment]
Hey @jnorell:

> Is there any way to customize solr-power to search within comments, just like the actual post content?

Yep, this should be possible, although would require a fair amount of work. 

At a high level, you'd need to:

1. Create a new Schema for comments.
2. Add the necessary WordPress hooks to push comment documents to Solr when comments are updated.
3. Overload `WP_Comment_Query` (in a manner similar to how Solr Power overloads `WP_Query`) to search Solr when comments are queried.

It'd be a good amount of work though, so you might want to consider other alternatives before you seriously explore it.
