### ISSUE TITLE
First search is very slow

### ISSUE THREAD

**Issue by ovangmbh** [pantheon-systems/solr-power#441]
I am using the docker image [kshaner/solr](https://hub.docker.com/r/kshaner/solr/) and everything is connecting as expected.

But every first search within over 80k posts is very slow (30 seconds). The next search with the same search parameters are very fast (under 1 second).

This is also if I use the WP_Query with the "solr-integrate" parameter.

**Comment by danielbachhuber** [comment]
Hi @ovangmbh,

Thanks for the report. Based on what you've described, this seems like it's a problem with the Docker image, not Solr Power.

Do you have any reason to believe the slowness is coming from Solr Power?
