### ISSUE TITLE
How to display document id and other details in a doucment?

### ISSUE THREAD

**Issue by muralib36** [pantheon-systems/solr-power#442]
I am using this plugin in my wordpress. Am trying to display document id and other details but i didn't find possible solution and also check in solarium api documentation. Can any one please suggest any solution.

**Comment by danielbachhuber** [comment]
Hi @muralib36,

I don't think you have direct access to the document ID without some modifications.

Could you describe what you're trying to do with a bit more detail? There might be some alternative way to achieve what you want.
