### ISSUE TITLE
woocommerce product indexing

### ISSUE THREAD

**Issue by akhillgopinath** [pantheon-systems/solr-power#46]
is there any way we can index only products ?

**Comment by ataylorme** [comment]
Hi @akhillgopinath,
There is a filter for `solr_post_types`. You can use this filter to have Solr Power only index products - instead of the default pages/posts.

**Comment by akhilgopinat** [comment]
thanks @ataylorme , this may help me to add custom facets for each product  category section , current default WooCommerce Widgets are heavy if we have more product attributes in the widget . So i am trying to build alternative way to get product category results from solr instead WooCommerce query . I will update you soon

**Comment by ataylorme** [comment]
@akhilgopinat We are currently working on a facet widget that will let you do exactly that.

Here is a screenshot of the work in progress. You can also follow along on the pull request, #78.

![solr-power-facet-widget](https://cloud.githubusercontent.com/assets/2133004/16842308/a1da0bea-49a2-11e6-88d6-4aff7a1f54c3.png)

**Comment by akhilgopinat** [comment]
Thanks @ataylorme

**Comment by ataylorme** [comment]
@akhilgopinat Check out [Solr Power 1.0](https://wordpress.org/plugins/solr-power/) which has the facet widget as well as `WP_Query` support, including custom post types.
