### ISSUE TITLE
Feature Request: Message on where the path of schema.xml is processed

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/solr-power#491]
We have a Pantheon user setup where they have a composer based WP installation which they have a custom `schema.xml` that was put in `/code/web/wp-content/uploads/solr-for-wordpress-on-pantheon` but it was not being recognized, so we tried putting the schema in `/code/web/wp/wp-content/uploads/solr-for-wordpress-on-pantheon`

Since we don't have any access to Solr logs, it would be nice if the complete path of the schema.xml is indicated here 
![Screen Shot 2021-03-08 at 12 03 16](https://user-images.githubusercontent.com/5098765/110272900-46beca80-8006-11eb-8532-8877899df89d.jpg) so we can easily know which schema is being processed. 

Thank you!

**Comment by danielbachhuber** [comment]
> Since we don't have any access to Solr logs, it would be nice if the complete path of the schema.xml is indicated here

Great suggestion! After #492 lands, the full path will be displayed on Pantheon:

<img width="962" alt="image" src="https://user-images.githubusercontent.com/36432/110354081-a14b2d00-7fec-11eb-8b1a-d1b4454de8db.png">
