### ISSUE TITLE
Drop Down Custom Fields - Feature Request

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/solr-power#52]
Feature Request

Create a drop down within **Indexing Options** that allows the user to index existing public custom fields

**Comment by ataylorme** [comment]
We have an admin option for custom fields which takes a comma separated list of meta keys.

I think a drop-down with all public custom fields would get very, very long. Also it would need to be a multi-select, not a standard drop-down to support indexing multiple custom fields.

I'm going to close this out but if you feel strongly about having a multi-select for public custom fields please re-open.
