### ISSUE TITLE
Drop Down Custom Post Types - Feature Request

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/solr-power#53]
Feature Request

Create a drop down within **Indexing Options** for indexing custom post types containing public content

**Comment by bmackinney** [comment]
In our conversation today, @allan23 suggested automatically indexing all post types that are publicly searchable by WordPress. That way if a user wants to exclude them, they can use `include exclude_from_search => true` when registering the post type with WordPress, and the search will function equivalently to MySQL WordPress search. 

@allan23 do you think this issue should change to "Add all publicly searchable post types to index by default"?

**Comment by mjlodge** [comment]
+1 on having all custom post types that are publicly searchable automatically indexed. That'd be easiest for us.
