### ISSUE TITLE
Send schema.xml automatically when deployed

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/solr-power#54]
schema.xml should be sent to Solr automatically when the plugin is deployed to another environment (Multidev to Dev and up to Live)

**Comment by joshkoenig** [comment]
Yeah, this will improve the customer experience quite a lot.

**Comment by joshkoenig** [comment]
What we need is to make a decision on how the plugin can know — based on API response — that the schema needs to be sent. Then it can do it. It's on Josh to figure out that response signature.

**Comment by ataylorme** [comment]
Fixed in PR #57 - closing out
