### ISSUE TITLE
Site Network, cannot apply facet option changes. 

### ISSUE THREAD

**Issue by anthonymendozagarces** [pantheon-systems/solr-power#541]
Getting these errors when trying to change facet options. 

PHP Notice:  Undefined index: solr-power-facet in /code/wp-content/plugins/solr-power/includes/class-solrpower-options.php on line 94

**Comment by scottbuscemi** [comment]
@anthonymendozagarces Thanks for the report - sorry for the issues. This is resolved with the latest version.
