### ISSUE TITLE
Divide by zero warning when posting a query

### ISSUE THREAD

**Issue by threeiem** [pantheon-systems/solr-power#566]
There is an assumption that there is more than one post to calculate posts_per_page in `class-solrpower-wp-query.php`.  This results in a warning.

```txt
PHP Warning:  Division by zero in /code/wp/wp-content/plugins/solr-power/includes/class-solrpower-wp-query.php on line 246
```

**Comment by scottbuscemi** [comment]
This has been fixed in today's 2.5.1 release, thank you for reporting!
