### ISSUE TITLE
Fatal error after updating to 2.4.4!

### ISSUE THREAD

**Issue by junaidbhura** [pantheon-systems/solr-power#579]
Hi there,

There's a fatal error after updating to `2.4.4`: `wp-content/plugins/solr-power/vendor/autoload.php`

```
 Fatal error: Uncaught Error: Failed opening required '/var/www/html/wp-content/plugins/solr-power/vendor/autoload.php'
```

Looks like that file is missing!

**Comment by pwtyler** [comment]
Thanks for the report @junaidbhura— looks like the release got tagged without the vendor directory. I'll get #580 out imminently with vendor/ back in place.

**Comment by pwtyler** [comment]
Alright, so closing this issue on PR merge was about 10 minutes premature, but 2.4.5 has deployed to wp.org and I just confirmed the .zip has the vendor directory restored. Sorry for the trouble!

**Comment by junaidbhura** [comment]
Thanks @pwtyler !
