### ISSUE TITLE
WP-CLI Integration

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/solr-power#58]
When you've got a lot of context to index, doing it via the web UI is _le suck_. 

Better would be this:

```shell
> wp-cli solr index --count=100
Indexing the next 100 posts
..........
Done! 100 posts sent to index in 7.16s
```

I think this plus a few other things could be enough for a 0.3 release!

**Comment by ericmann** [comment]
+100

**Comment by danielbachhuber** [comment]
Happy to review this implementation. Also, you could set up integration tests for the WP-CLI commands using https://github.com/wp-cli/wp-cli/wiki/Package-Functional-Tests

**Comment by rachelwhitton** [comment]
+1
@allan23 I'm happy to assist with automating the integration tests on this one if needed
