### ISSUE TITLE
We shouldn't block on AJAX/Admin use-cases

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/solr-power#59]
Right now we bail if the request is in the admin area of is being done via AJAX. However, if we want to support use-cases like autocomplete or general purpose WP_Query() overriding, we probably can't continue to do that:

https://github.com/pantheon-systems/solr-power/blame/master/includes/class-solrpower-wp-query.php#L29

**Comment by bmackinney** [comment]
@rachelwhitton
