### ISSUE TITLE
Enable full query interface

### ISSUE THREAD

**Issue by erik-pantheon** [pantheon-systems/solr-power#63]
Currently, the interface for the WP Solr plugin only allows searches for string values. While this is useful for the layman, most developers who are using Solr require the ability to test more complicated queries. The Pantheon's Drupal Solr Module does this well. One can run something like:

/select?fl=label,bundle,ts_ol_full_text&fq=bundle:bill%20AND%20ts_ol_full_text:property&wt=json

...and return results with the Drupal Solr module. Being able to do the same in Solr Powr would be invaluable.

**Comment by allan23** [comment]
@ataylorme  Would this just be an extension of the options page query?

**Comment by ataylorme** [comment]
@allan23 Yes, I think @erik-pantheon is looking for a pass through allowing direct queries to the Solr Instance. Erik, can you confirm?

This is lower priority than items in the 1.0 milestone.

**Comment by ataylorme** [comment]
No discussion on this in months, closing out. Erik please re-open if this is still something you're looking for.
