### ISSUE TITLE
pager bug

### ISSUE THREAD

**Issue by rachelwhitton** [pantheon-systems/solr-power#64]
Page-links for paginated posts produce 404s

Disabling the **Output Result Pager** option does not seem to remove page-links as assumed (not sure that's the intent behind the option though?)

![screen shot 2016-03-25 at 4 15 06 pm](https://cloud.githubusercontent.com/assets/10119525/14054608/81b397c4-f2a8-11e5-8e90-dd68be62d763.png)
<hr>
![screen shot 2016-03-25 at 3 59 58 pm](https://cloud.githubusercontent.com/assets/10119525/14054613/837d4e4c-f2a8-11e5-805d-7b031b124d19.png)

**Comment by joshkoenig** [comment]
Possibly addressed in #67. Going to work on replicating now.

**Comment by joshkoenig** [comment]
Should be fixed after #67
