### ISSUE TITLE
[BUGS-9162] `wp solr delete <post_id>` command does not work

### ISSUE THREAD

**Issue by jazzsequence** [pantheon-systems/solr-power#640]
When using the Solr Power plugin with WordPress, the wp solr delete <post_id> command is documented, but it seems like it does not currently do anything currently.

Our Documentation for Solr Power says there is a wp solr delete command:
[Solr Search for WordPress](https://wordpress.org/plugins/solr-power/) 

The response from WP-CLi says it worked. But it doesn’t seem to actually remove the item from the Solr search results.

### Steps to Reproduce

On test, I made sure that the Solr content was indexed. After I did that, I searched “world” and Post 1, the “hello world” post, was the only result. [You searched for world - Dan Ficker's Wordpress Megasite](https://test.wordpress-test.da-man.com/?s=world) 

I then ran this command:

```
terminus wp <site>.<env> -- solr delete 1
```

It responded with this:

```
Removed post 1 from the index.
Success: Specified posts removed from the index.
```

However, the search of “world” on the site remains unchanged, which indicates the post has not been removed from the index.

**Comment by pwtyler** [comment]
This appears to have been a page cache issue.
