### ISSUE TITLE
Test and document that we're all good w/WordPress 4.5

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/solr-power#66]
I think we can jump from 4.3 to 4.5 in the README.

In the future this could be part of the automated test/release process. :)

**Comment by joshkoenig** [comment]
@allan23 Let's close if we're good with this. I did my testing on 4.5 recently, but would be nice if you can confirm.

I moved #54 to 0.4 since I think we should think about it more. Forcing a visit to the admin screen doesn't seem "good enough" to me. I'd say lets roll forward with this release as it has some pretty critical bugfixes and feature additions.

**Comment by allan23** [comment]
@joshkoenig Everything is working fine on the 4.5 front.

**Comment by joshkoenig** [comment]
Ok let's roll!
