### ISSUE TITLE
De-fork Solarium

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/solr-power#72]
Pre-requisite for #14 - we have a little shim in Solarium. We should subclass instead like the proper OOPers that we are.

**Comment by ataylorme** [comment]
Removing the 0.4 milestone. Since this isn't a new feature, just some internal cleanup, it can be a patch version bump instead of a minor release and shouldn't hold up other, new features for 0.4

**Comment by ataylorme** [comment]
@allan23 Check out @stevector's [commit on removing the Solarium patch for the Drupal module](https://github.com/stevector/search_api_pantheon/pull/19/files#diff-ab66d9a69b5ed6f6025041ee470895d5R1).

**Comment by stevector** [comment]
I did some cleanup on the subclass: https://github.com/stevector/search_api_pantheon/pull/21/files

**Comment by ataylorme** [comment]
Thanks Steve!

**Comment by danielbachhuber** [comment]
@ataylorme @allan23 Does this mean it's not safe to run `composer install`, because there's some forked code committed to the `vendor` directory?

**Comment by ataylorme** [comment]
@danielbachhuber Started this in PR #105. Would love to chat with you or @greg-1-anderson on getting our `vendor` directory out of the repo.

**Comment by ataylorme** [comment]
Merged in #106
