### ISSUE TITLE
Add wp-cli support

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/solr-power#75]
We should support actions from the plugins settings page in wp-cli.
* Check Server Settings
* Optimize Index
* Delete All
* Repost schema.xml
* Index Searchable Post Types

We should also consider informative commands.
* `info` should return ping status, Solr server IP address, Solr server port and Solr server path.
* `stats` should return a table of indexing status by post type

I think these two would create a minimum viable product. Additional commands can be items from the indexing tab in the plugin settings such as setting the default search operator.

**Comment by danielbachhuber** [comment]
@ataylorme Want some help with this?

**Comment by ataylorme** [comment]
As @allan23 pointed out there is some initial WP-CLI support ([see here](https://github.com/pantheon-systems/solr-power/blob/master/includes/class-solrpower-cli.php)) but the coverage is lacking.

We would like to expand the coverage as well as add a wiki page to Github with documentation on available commands.

**Comment by ataylorme** [comment]
Merged in #104

**Comment by ataylorme** [comment]
Documentation added to `README.md`. Since this is displayed on the repo home page I don't think there is a need to add to the wiki as well.
