### ISSUE TITLE
Use Behat to test Solr Power on Pantheon

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/solr-power#79]
On a couple other Pantheon plugins now, we're using Behat to verify the plugin works as expected on Pantheon (e.g. https://github.com/pantheon-systems/wp-redis/pull/103). It would be cool if Solr Power did this too.

At a high-level, here's how it works:

* We're using Circle (in addition to Travis) to automate the creation and destruction of a Pantheon environment for an existing Pantheon site. In accordance to our existing naming scheme, you'd use `solr-power` as the site name.
* `bin/behat-prepare.sh` creates the environment, pushes the current plugin copy up, activates it, and performs any other configuration steps needed.
* `bin/behat-test.sh` runs the Behat tests against the created environment
* `bin/behat-cleanup.sh` removes the environment after the tests are done running.

You can likely copy and lightly modify most of the referenced pull request. I'd be keen to get your input on the documentation, and implementation generally.

cc @stevector

**Comment by danielbachhuber** [comment]
After #95 lands, it would be nice to finish this issue up with a few more scenarios for basic plugin operation.

**Comment by ataylorme** [comment]
@danielbachhuber Want me to leave this issue open until we get some more tests?

**Comment by ataylorme** [comment]
Raised #116 to create additional Behat tests in the future. Since we have basic coverage I'm closing this out.
