### ISSUE TITLE
Documentation Needed For Filters

### ISSUE THREAD

**Issue by allan23** [pantheon-systems/solr-power#83]
It will be beneficial for developers to have all filters in this plugin documented on the GitHub Wiki.

**Comment by ataylorme** [comment]
Closed this prematurely. We still need to document the filters on the project Wiki.

**Comment by Ritesh-patel** [comment]
Added wiki page https://github.com/pantheon-systems/solr-power/wiki

**Comment by ataylorme** [comment]
Great, thank you @Ritesh-patel. Can you also add this to `readme.txt` and `README.md`? Note that if you modify `readme.txt` there is a Grunt task to generate `README.md`
