### ISSUE TITLE
Use WPCS to ensure the codebase adheres to WordPress Coding Standards

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/solr-power#85]
WPCS (https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards) is a series of PHP Codesniffer Sniffs to ensure a codebase adheres to WordPress' coding standards. We should set it up for the project, as we already have for https://github.com/pantheon-systems/wp-redis et al.

Setting up WPCS involves:
- [x] Defining the dependencies in composer.json https://github.com/pantheon-systems/wp-redis/blob/master/composer.json#L11-L12
- [x] Adding the `grunt phpcs` step, and defining associated dependencies https://github.com/pantheon-systems/wp-redis/blob/master/Gruntfile.js#L20-L28
- [x] Having Travis call the Codesniffer step https://github.com/pantheon-systems/wp-redis/blob/master/.travis.yml#L39-L43

Once it's set up, we'll need to:

* [x] Update all files to adhere to WPCS

**Comment by ataylorme** [comment]
I agree wo should be using [WordPress coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/).

Outside of automation and formatting updates should be made independently of other commits.

**Comment by ChrisWiegman** [comment]
I'd be happy to run with this as it will stop my IDE from yelling at me every time I save a file. Feel free to have @allan23 assign to me.

**Comment by ataylorme** [comment]
@ChrisWiegman I assigned most items to @allan23 but feel free to grab anything from the [1.0 milestone](https://github.com/pantheon-systems/solr-power/milestone/5) to work on.

**Comment by ataylorme** [comment]
Punting this so we can get `1.1` out.

**Comment by ataylorme** [comment]
When working on this the first priority should be code comments. Once all code is properly commented/detailed we can work on formatting.

**Comment by danielbachhuber** [comment]
🚢  :shipit: 🎉
