### ISSUE TITLE
Document local setup steps

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/solr-power#86]
For users who want to work with the plugin locally, we should have a short "how-to" guide for getting Solr running locally.

**Comment by jlambe** [comment]
👍

**Comment by danielbachhuber** [comment]
Just so it's documented, I tried setting this up locally by connecting to a Pantheon Solr instance. However, it appears the Pantheon Solr instance is behind a firewall, and doesn't respond to pings from an external network.

**Comment by ataylorme** [comment]
Merged in #92
